--use BD_ANALITICO
--GO

--CREATE PROCEDURE KR_MATRIZ_VEN
--	@CodPais CHAR(2),
--	@AnioCampana CHAR(6)

--AS

--BEGIN

declare 
     @AnioCampanamenos1 CHAR(6),
	 @AnioCampanamenos2 CHAR(6),
	 @AnioCampanamenos3 CHAR(6),
	 @AnioCampanamenos4 CHAR(6),
	 @AnioCampanamenos5 CHAR(6),
	 @AnioCampanamenos8 CHAR(6),
	 @AnioCampanamenos11 CHAR(6),
	 @AnioCampanamenos14 CHAR(6),
	 @AnioCampanamenos17 CHAR(6),
	 @CodPais CHAR(2),
	 @AnioCampana CHAR(6)

set @CodPais = 'PE'
set @AnioCampana = '201716'
set @AnioCampanamenos1 = dbo.CalculaAnioCampana(@AnioCampana, -1)
set @AnioCampanamenos2 = dbo.CalculaAnioCampana(@AnioCampana, -2)
set @AnioCampanamenos3 = dbo.CalculaAnioCampana(@AnioCampana, -3)
set @AnioCampanamenos4 = dbo.CalculaAnioCampana(@AnioCampana, -4)
set @AnioCampanamenos5 = dbo.CalculaAnioCampana(@AnioCampana, -5)
set @AnioCampanamenos8 = dbo.CalculaAnioCampana(@AnioCampana, -8)
set @AnioCampanamenos11 = dbo.CalculaAnioCampana(@AnioCampana, -11)
set @AnioCampanamenos14 = dbo.CalculaAnioCampana(@AnioCampana, -14)
set @AnioCampanamenos17 = dbo.CalculaAnioCampana(@AnioCampana, -17)

----------------Unidades y Facturación

IF OBJECT_ID('tempdb..#TMP_FVTAPROEBECAM') IS NOT NULL DROP TABLE #TMP_FVTAPROEBECAM

SELECT A.CodPais, A.AnioCampana,A.PkEbelista,
		SUM(RealUUVendidas) as RealUUVendidas,
		SUM(RealUUFaltantes) as RealUUFaltantes,
		SUM(RealUUDevueltas) as RealUUDevueltas, 
		SUM(RealUUAnuladas) as RealUUAnuladas,
		SUM(RealVtaMNNeto) as RealVtaMNNeto,
		SUM(OportunidadAhorroMN) as OportunidadAhorroMN
INTO #TMP_FVTAPROEBECAM
FROM [DWH_ANALITICO].[dbo].[DWH_FVTAPROEBECAM]  A
INNER JOIN  [DWH_ANALITICO].[dbo].[DWH_DTIPOOFERTA] B  ON A.PKTipoOferta=B.PKTipoOferta AND B.CodPais = A.CodPais 
WHERE A.AnioCampana BETWEEN @AnioCampanamenos17 AND @AnioCampana AND B.codtipoprofit = '01' AND A.RealVtaMNNeto > 0 
	AND A.CodPais = @CodPais AND a.AnioCampana = a.AnioCampanaRef
GROUP BY A.CodPais, A.AnioCampana,A.PkEbelista

CREATE INDEX IDX_Pais_EbeCam ON #TMP_FVTAPROEBECAM (CodPais, AnioCampana, PkEbelista)

IF OBJECT_ID('tempdb..#KR_VEN_CAMP_TOT') IS NOT NULL DROP TABLE #KR_VEN_CAMP_TOT

;WITH EbelistaUC AS
(
	SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/1 as UC_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/1 as UC_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/1 as UC_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/1 as UC_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/1 as UC_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/1 as UC_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampana
	GROUP BY A.CodPais, A.PkEbelista
), EbelistaCampanaMenos1 AS
(
	SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/2 as U2C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/2 as U2C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/2 as U2C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/2 as U2C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/2 as U2C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/2 as U2C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/1 AS U2C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/1 AS U2C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/1 AS U2C_RealVtaMNNeto_SUC,
			AVG(RealVtaMNNeto ) AS U2C_PRO_RealVtaMNNeto ,
			AVG(OportunidadAhorroMN ) AS U2C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U2C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U2C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U2C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U2C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U2C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U2C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U2C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U2C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U2C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U2C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U2C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U2C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U2C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U2C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U2C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos1
	GROUP BY A.CodPais, A.PkEbelista
),EbelistaCampanaMenos2 AS 
(

	SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/3 as U3C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/3 as U3C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/3 as U3C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/3 as U3C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/3 as U3C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/3 as U3C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/2 AS U3C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/2 AS U3C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/2 AS U3C_RealVtaMNNeto_SUC,
			AVG(RealVtaMNNeto ) AS U3C_PRO_RealVtaMNNeto ,
			AVG(OportunidadAhorroMN ) AS U3C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U3C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U3C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U3C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U3C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U3C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U3C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U3C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U3C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U3C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U3C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U3C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U3C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U3C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U3C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U3C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos2
	GROUP BY A.CodPais, A.PkEbelista
),EbelistaCampanaMenos3 AS 
(

SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/4 as U4C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/4 as U4C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/4 as U4C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/4 as U4C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/4 as U4C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/4 as U4C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/3 AS U4C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/3 AS U4C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/3 AS U4C_RealVtaMNNeto_SUC,
			AVG(RealVtaMNNeto ) AS U4C_PRO_RealVtaMNNeto ,
			AVG(OportunidadAhorroMN ) AS U4C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U4C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U4C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U4C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U4C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U4C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U4C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U4C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U4C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U4C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U4C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U4C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U4C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U4C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U4C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U4C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos3
	GROUP BY A.CodPais, A.PkEbelista
),EbelistaCampanaMenos4 AS 
(

SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/5 as U5C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/5 as U5C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/5 as U5C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/5 as U5C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/5 as U5C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/5 as U5C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/4 AS U5C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/4 AS U5C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/4 AS U5C_RealVtaMNNeto_SUC,
			AVG(RealVtaMNNeto ) AS U5C_PRO_RealVtaMNNeto,
			AVG(OportunidadAhorroMN ) AS U5C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U5C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U5C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U5C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U5C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U5C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U5C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U5C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U5C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U5C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U5C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U5C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U5C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U5C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U5C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U5C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos4
	GROUP BY A.CodPais, A.PkEbelista
),EbelistaCampanaMenos5 AS 
(

	SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/6 as U6C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/6 as U6C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/6 as U6C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/6 as U6C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/6 as U6C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/6 as U6C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/5 AS U6C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/5 AS U6C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/5 AS U6C_RealVtaMNNeto_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealUUVendidas ELSE 0 END)/3 AS U3C_RealUUVendidas_II,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN OportunidadAhorroMN ELSE 0 END)/3 AS U3C_OportunidadAhorroMN_II,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealVtaMNNeto ELSE 0 END)/3 AS U3C_RealVtaMNNeto_II,
			AVG(RealVtaMNNeto ) AS U6C_PRO_RealVtaMNNeto ,
			AVG(OportunidadAhorroMN ) AS U6C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U6C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U6C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U6C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U6C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U6C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U6C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U6C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U6C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U6C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U6C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U6C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U6C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U6C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U6C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U6C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos5
	GROUP BY A.CodPais, A.PkEbelista
),EbelistaCampanaMenos8 AS
(
SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/9 as U9C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/9 as U9C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/9 as U9C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/9 as U9C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/9 as U9C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/9 as U9C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/8 AS U9C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/8 AS U9C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/8 AS U9C_RealVtaMNNeto_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealUUVendidas ELSE 0 END)/6 AS U3C_RealUUVendidas_SUC_III,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN OportunidadAhorroMN ELSE 0 END)/6 AS U3C_OportunidadAhorroMN_SUC_III,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealVtaMNNeto ELSE 0 END)/6 AS U3C_RealVtaMNNeto_SUC_III,
			AVG(RealVtaMNNeto ) AS U9C_PRO_RealVtaMNNeto ,
			AVG(OportunidadAhorroMN ) AS U9C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U9C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U9C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U9C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U9C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U9C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U9C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U9C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U9C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U9C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U9C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U9C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U9C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U9C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U9C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U9C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos8
	GROUP BY A.CodPais, A.PkEbelista
),EbelistaCampanaMenos11 AS
(

	SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/12 as U12C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/12 as U12C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/12 as U12C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/12 as U12C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/12 as U12C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/12 as U12C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/11 AS U12C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/11 AS U12C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/11 AS U12C_RealVtaMNNeto_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealUUVendidas ELSE 0 END)/9 AS U6C_RealUUVendidas_SUCIV,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN OportunidadAhorroMN ELSE 0 END)/9 AS U6C_OportunidadAhorroMN_SUCIV,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealVtaMNNeto ELSE 0 END)/9 AS U6C_RealVtaMNNeto_SUCIV,
			AVG(RealVtaMNNeto ) AS U12C_PRO_RealVtaMNNeto,
			AVG(OportunidadAhorroMN ) AS U12C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U12C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U12C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U12C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U12C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U12C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U12C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U12C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U12C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U12C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U12C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U12C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U12C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U12C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U12C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U12C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos11
	GROUP BY A.CodPais, A.PkEbelista
),EbelistaCampanaMenos14 AS
(

	SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/15 as U15C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/15 as U15C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/15 as U15C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/15 as U15C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/15 as U15C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/15 as U15C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/14 AS U15C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/14 AS U15C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/14 AS U15C_RealVtaMNNeto_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealUUVendidas ELSE 0 END)/12 AS U9C_RealUUVendidas_V,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN OportunidadAhorroMN ELSE 0 END)/12 AS U9C_OportunidadAhorroMN_V,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealVtaMNNeto ELSE 0 END)/12 AS U9C_RealVtaMNNeto_V,
			AVG(RealVtaMNNeto ) AS U15C_PRO_RealVtaMNNeto,
			AVG(OportunidadAhorroMN ) AS U15C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U15C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U15C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U15C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U15C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U15C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U15C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U15C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U15C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U15C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U15C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U15C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U15C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U15C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U15C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U15C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos14
	GROUP BY A.CodPais, A.PkEbelista
),EbelistaCampanaMenos17 AS
(
	SELECT A.CodPais, A.PkEbelista, 
			1.0*SUM(RealUUVendidas)/17 as U18C_RealUUVendidas,
			1.0*SUM(RealUUFaltantes)/17 as U18C_RealUUFaltantes,
			1.0*SUM(RealUUDevueltas)/17 as U18C_RealUUDevueltas, 
			1.0*SUM(RealUUAnuladas)/17 as U18C_RealUUAnuladas,
			1.0*SUM(RealVtaMNNeto)/17 as U18C_RealVtaMNNeto,
			1.0*SUM(OportunidadAhorroMN)/17 as U18C_OportunidadAhorroMN,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealUUVendidas ELSE 0 END)/17 AS U18C_RealUUVendidas_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN OportunidadAhorroMN ELSE 0 END)/17 AS U18C_OportunidadAhorroMN_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampana THEN RealVtaMNNeto ELSE 0 END)/17 AS U18C_RealVtaMNNeto_SUC,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealUUVendidas ELSE 0 END)/15 AS U12C_RealUUVendidas_VI,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN OportunidadAhorroMN ELSE 0 END)/15 AS U12C_OportunidadAhorroMN_VI,
			1.0*SUM(CASE WHEN AnioCampana < @AnioCampanamenos2 THEN RealVtaMNNeto ELSE 0 END)/15 AS U12C_RealVtaMNNeto_VI,
			AVG(RealVtaMNNeto ) AS U18C_PRO_RealVtaMNNeto,
			AVG(OportunidadAhorroMN ) AS U18C_PRO_OportunidadAhorroMN ,
			STDEV(RealUUVendidas ) AS U18C_DESV_RealUUVendidas ,
			STDEV(RealUUDevueltas) AS U18C_DESV_RealUUDevueltas,
			STDEV(RealUUAnuladas) AS U18C_DESV_RealUUAnuladas,
			STDEV(RealVtaMNNeto) AS U18C_DESV_RealVtaMNNeto,
			STDEV(OportunidadAhorroMN) AS U18C_DESV_OportunidadAhorroMN,
			MIN(RealUUVendidas ) AS U18C_MIN_RealUUVendidas ,
			MIN(RealUUDevueltas) AS U18C_MIN_RealUUDevueltas,
			MIN(RealUUAnuladas) AS U18C_MIN_RealUUAnuladas,
			MIN(RealVtaMNNeto) AS U18C_MIN_RealVtaMNNeto,
			MIN(OportunidadAhorroMN) AS U18C_MIN_OportunidadAhorroMN,
			MAX(RealUUVendidas ) AS U18C_MAX_RealUUVendidas ,
			MAX(RealUUDevueltas) AS U18C_MAX_RealUUDevueltas,
			MAX(RealUUAnuladas) AS U18C_MAX_RealUUAnuladas,
			MAX(RealVtaMNNeto) AS U18C_MAX_RealVtaMNNeto,
			MAX(OportunidadAhorroMN) AS U18C_MAX_OportunidadAhorroMN
	FROM #TMP_FVTAPROEBECAM A
	WHERE AnioCampana >= @AnioCampanamenos17
	GROUP BY A.CodPais, A.PkEbelista
)
SELECT  @AnioCampana as AnioCampana,
		A.CodPais,
		A.PkEbelista,
		ISNULL(J.UC_RealUUVendidas,0)			AS UC_RealUUVendidas,         
		ISNULL(I.U2C_RealUUVendidas,0)			AS U2C_RealUUVendidas,
		ISNULL(H.U3C_RealUUVendidas,0)			AS U3C_RealUUVendidas,
		ISNULL(G.U4C_RealUUVendidas,0)			AS U4C_RealUUVendidas,
		ISNULL(F.U5C_RealUUVendidas,0)			AS U5C_RealUUVendidas,
		ISNULL(E.U6C_RealUUVendidas,0)			AS U6C_RealUUVendidas,
		ISNULL(D.U9C_RealUUVendidas,0)			AS U9C_RealUUVendidas,
		ISNULL(C.U12C_RealUUVendidas,0)			AS U12C_RealUUVendidas,
		ISNULL(B.U15C_RealUUVendidas,0)			AS U15C_RealUUVendidas,
		ISNULL(A.U18C_RealUUVendidas,0)			AS U18C_RealUUVendidas,
		ISNULL(J.UC_RealUUFaltantes,0)			AS UC_RealUUFaltantes,
		ISNULL(I.U2C_RealUUFaltantes,0)			AS U2C_RealUUFaltantes,
		ISNULL(H.U3C_RealUUFaltantes,0)			AS U3C_RealUUFaltantes,
		ISNULL(G.U4C_RealUUFaltantes,0)			AS U4C_RealUUFaltantes,
		ISNULL(F.U5C_RealUUFaltantes,0)			AS U5C_RealUUFaltantes,
		ISNULL(E.U6C_RealUUFaltantes,0)			AS U6C_RealUUFaltantes,
		ISNULL(D.U9C_RealUUFaltantes,0)			AS U9C_RealUUFaltantes,
		ISNULL(C.U12C_RealUUFaltantes,0)			AS U12C_RealUUFaltantes,
		ISNULL(B.U15C_RealUUFaltantes,0)			AS U15C_RealUUFaltantes,
		ISNULL(A.U18C_RealUUFaltantes,0)			AS U18C_RealUUFaltantes,
		ISNULL(J.UC_RealUUDevueltas,0)			AS UC_RealUUDevueltas,
		ISNULL(I.U2C_RealUUDevueltas,0)				AS U2C_RealUUDevueltas,
		ISNULL(H.U3C_RealUUDevueltas,0)			AS U3C_RealUUDevueltas,
		ISNULL(G.U4C_RealUUDevueltas,0)			AS U4C_RealUUDevueltas,
		ISNULL(F.U5C_RealUUDevueltas,0)			AS U5C_RealUUDevueltas,
		ISNULL(E.U6C_RealUUDevueltas,0)			AS U6C_RealUUDevueltas,
		ISNULL(D.U9C_RealUUDevueltas,0)			AS U9C_RealUUDevueltas,
		ISNULL(C.U12C_RealUUDevueltas,0)			AS U12C_RealUUDevueltas,
		ISNULL(B.U15C_RealUUDevueltas,0)			AS U15C_RealUUDevueltas,
		ISNULL(A.U18C_RealUUDevueltas,0)			AS U18C_RealUUDevueltas,
		ISNULL(J.UC_RealUUAnuladas,0)			AS UC_RealUUAnuladas,
		ISNULL(I.U2C_RealUUAnuladas,0)				AS U2C_RealUUAnuladas,
		ISNULL(H.U3C_RealUUAnuladas,0)			AS U3C_RealUUAnuladas,
		ISNULL(G.U4C_RealUUAnuladas,0)			AS U4C_RealUUAnuladas,
		ISNULL(F.U5C_RealUUAnuladas,0)			AS U5C_RealUUAnuladas,
		ISNULL(E.U6C_RealUUAnuladas,0)			AS U6C_RealUUAnuladas,
		ISNULL(D.U9C_RealUUAnuladas,0)			AS U9C_RealUUAnuladas,
		ISNULL(C.U12C_RealUUAnuladas,0)				AS U12C_RealUUAnuladas,
		ISNULL(B.U15C_RealUUAnuladas,0)			AS U15C_RealUUAnuladas,
		ISNULL(A.U18C_RealUUAnuladas,0)			AS U18C_RealUUAnuladas,
		ISNULL(J.UC_RealVtaMNNeto,0)			AS UC_RealVtaMNNeto,
		ISNULL(I.U2C_RealVtaMNNeto,0)				AS U2C_RealVtaMNNeto,
		ISNULL(H.U3C_RealVtaMNNeto,0)				AS U3C_RealVtaMNNeto,
		ISNULL(G.U4C_RealVtaMNNeto,0)				AS U4C_RealVtaMNNeto,
		ISNULL(F.U5C_RealVtaMNNeto,0)				AS U5C_RealVtaMNNeto,
		ISNULL(E.U6C_RealVtaMNNeto,0)				AS U6C_RealVtaMNNeto,
		ISNULL(D.U9C_RealVtaMNNeto,0)				AS U9C_RealVtaMNNeto,
		ISNULL(C.U12C_RealVtaMNNeto,0)				AS U12C_RealVtaMNNeto,
		ISNULL(B.U15C_RealVtaMNNeto,0)			AS U15C_RealVtaMNNeto,
		ISNULL(A.U18C_RealVtaMNNeto,0)			AS U18C_RealVtaMNNeto,
		ISNULL(J.UC_OportunidadAhorroMN,0)			AS UC_OportunidadAhorroMN,
		ISNULL(I.U2C_OportunidadAhorroMN,0)			AS U2C_OportunidadAhorroMN,
		ISNULL(H.U3C_OportunidadAhorroMN,0)		AS U3C_OportunidadAhorroMN,
		ISNULL(G.U4C_OportunidadAhorroMN,0)		AS U4C_OportunidadAhorroMN,
		ISNULL(F.U5C_OportunidadAhorroMN,0)		AS U5C_OportunidadAhorroMN,
		ISNULL(E.U6C_OportunidadAhorroMN,0)		AS U6C_OportunidadAhorroMN,
		ISNULL(D.U9C_OportunidadAhorroMN,0)		AS U9C_OportunidadAhorroMN,
		ISNULL(C.U12C_OportunidadAhorroMN,0)		AS U12C_OportunidadAhorroMN,
		ISNULL(B.U15C_OportunidadAhorroMN,0)		AS U15C_OportunidadAhorroMN,
		ISNULL(A.U18C_OportunidadAhorroMN,0)		AS U18C_OportunidadAhorroMN,
		ISNULL(I.U2C_PRO_RealVtaMNNeto,0) AS U2C_PRO_RealVtaMNNeto, 
		ISNULL(I.U2C_PRO_OportunidadAhorroMN,0)		AS U2C_PRO_OportunidadAhorroMN,
		ISNULL(I.U2C_DESV_RealUUVendidas,0)	AS U2C_DESV_RealUUVendidas,
		ISNULL(I.U2C_DESV_RealUUDevueltas,0)		AS U2C_DESV_RealUUDevueltas,
		ISNULL(I.U2C_DESV_RealUUAnuladas,0)		AS U2C_DESV_RealUUAnuladas,
		ISNULL(I.U2C_DESV_RealVtaMNNeto,0)		AS U2C_DESV_RealVtaMNNeto,
		ISNULL(I.U2C_DESV_OportunidadAhorroMN,0)		AS U2C_DESV_OportunidadAhorroMN,
		ISNULL(I.U2C_MIN_RealUUVendidas,0)	AS U2C_MIN_RealUUVendidas,
		ISNULL(I.U2C_MIN_RealUUDevueltas,0)			AS U2C_MIN_RealUUDevueltas,
		ISNULL(I.U2C_MIN_RealUUAnuladas,0)		AS U2C_MIN_RealUUAnuladas,
		ISNULL(I.U2C_MIN_RealVtaMNNeto,0)		AS U2C_MIN_RealVtaMNNeto,
		ISNULL(I.U2C_MIN_OportunidadAhorroMN,0)		AS U2C_MIN_OportunidadAhorroMN,
		ISNULL(I.U2C_MAX_RealUUVendidas,0)	AS U2C_MAX_RealUUVendidas,
		ISNULL(I.U2C_MAX_RealUUDevueltas,0)			AS U2C_MAX_RealUUDevueltas,
		ISNULL(I.U2C_MAX_RealUUAnuladas,0)		AS U2C_MAX_RealUUAnuladas,
		ISNULL(I.U2C_MAX_RealVtaMNNeto,0)		AS U2C_MAX_RealVtaMNNeto,
		ISNULL(I.U2C_MAX_OportunidadAhorroMN,0) AS U2C_MAX_OportunidadAhorroMN,
		ISNULL(H.U3C_MAX_OportunidadAhorroMN,0) AS U3C_MAX_OportunidadAhorroMN,
		ISNULL(H.U3C_PRO_RealVtaMNNeto,0) AS U3C_PRO_RealVtaMNNeto,
		ISNULL(H.U3C_PRO_OportunidadAhorroMN,0)		AS U3C_PRO_OportunidadAhorroMN,
		ISNULL(H.U3C_DESV_RealUUVendidas,0)		AS U3C_DESV_RealUUVendidas,
		ISNULL(H.U3C_DESV_RealUUDevueltas,0)		AS U3C_DESV_RealUUDevueltas,
		ISNULL(H.U3C_DESV_RealUUAnuladas,0)		AS U3C_DESV_RealUUAnuladas,
		ISNULL(H.U3C_DESV_RealVtaMNNeto,0)		AS U3C_DESV_RealVtaMNNeto,
		ISNULL(H.U3C_DESV_OportunidadAhorroMN,0)		AS U3C_DESV_OportunidadAhorroMN,
		ISNULL(H.U3C_MIN_RealUUVendidas,0)	AS U3C_MIN_RealUUVendidas,
		ISNULL(H.U3C_MIN_RealUUDevueltas,0)			AS U3C_MIN_RealUUDevueltas,
		ISNULL(H.U3C_MIN_RealUUAnuladas,0)		AS U3C_MIN_RealUUAnuladas,
		ISNULL(H.U3C_MIN_RealVtaMNNeto,	0)		AS U3C_MIN_RealVtaMNNeto,
		ISNULL(H.U3C_MIN_OportunidadAhorroMN,0)		AS U3C_MIN_OportunidadAhorroMN,
		ISNULL(H.U3C_MAX_RealUUVendidas,0)	AS U3C_MAX_RealUUVendidas,
		ISNULL(H.U3C_MAX_RealUUDevueltas,0)			AS U3C_MAX_RealUUDevueltas,
		ISNULL(H.U3C_MAX_RealUUAnuladas,0)		AS U3C_MAX_RealUUAnuladas,
		ISNULL(H.U3C_MAX_RealVtaMNNeto,	0)		AS U3C_MAX_RealVtaMNNeto,
		ISNULL(G.U4C_MAX_OportunidadAhorroMN,0) AS U4C_MAX_OportunidadAhorroMN,
		ISNULL(G.U4C_PRO_RealVtaMNNeto,0) AS U4C_PRO_RealVtaMNNeto,
		ISNULL(G.U4C_PRO_OportunidadAhorroMN,0)		AS U4C_PRO_OportunidadAhorroMN,
		ISNULL(G.U4C_DESV_RealUUVendidas,0)	AS U4C_DESV_RealUUVendidas,
		ISNULL(G.U4C_DESV_RealUUDevueltas,0)		AS U4C_DESV_RealUUDevueltas,
		ISNULL(G.U4C_DESV_RealUUAnuladas,0)		AS U4C_DESV_RealUUAnuladas,
		ISNULL(G.U4C_DESV_RealVtaMNNeto,0)		AS U4C_DESV_RealVtaMNNeto,
		ISNULL(G.U4C_DESV_OportunidadAhorroMN,0)		AS U4C_DESV_OportunidadAhorroMN,
		ISNULL(G.U4C_MIN_RealUUVendidas,0)	AS U4C_MIN_RealUUVendidas,
		ISNULL(G.U4C_MIN_RealUUDevueltas,0)			AS U4C_MIN_RealUUDevueltas,
		ISNULL(G.U4C_MIN_RealUUAnuladas,0)		AS U4C_MIN_RealUUAnuladas,
		ISNULL(G.U4C_MIN_RealVtaMNNeto,	0)		AS U4C_MIN_RealVtaMNNeto,
		ISNULL(G.U4C_MIN_OportunidadAhorroMN,0)		AS U4C_MIN_OportunidadAhorroMN,
		ISNULL(G.U4C_MAX_RealUUVendidas,0)	AS U4C_MAX_RealUUVendidas,
		ISNULL(G.U4C_MAX_RealUUDevueltas,0)			AS U4C_MAX_RealUUDevueltas,
		ISNULL(G.U4C_MAX_RealUUAnuladas,0)		AS U4C_MAX_RealUUAnuladas,
		ISNULL(G.U4C_MAX_RealVtaMNNeto,0)		AS U4C_MAX_RealVtaMNNeto,
		ISNULL(F.U5C_MAX_OportunidadAhorroMN,0) AS U5C_MAX_OportunidadAhorroMN,
		ISNULL(F.U5C_PRO_RealVtaMNNeto,0) AS U5C_PRO_RealVtaMNNeto,
		ISNULL(F.U5C_PRO_OportunidadAhorroMN,0)		AS U5C_PRO_OportunidadAhorroMN,
		ISNULL(F.U5C_DESV_RealUUVendidas,0)	AS U5C_DESV_RealUUVendidas,
		ISNULL(F.U5C_DESV_RealUUDevueltas,0)			AS U5C_DESV_RealUUDevueltas,
		ISNULL(F.U5C_DESV_RealUUAnuladas,0)		AS U5C_DESV_RealUUAnuladas,
		ISNULL(F.U5C_DESV_RealVtaMNNeto,0)		AS U5C_DESV_RealVtaMNNeto,
		ISNULL(F.U5C_DESV_OportunidadAhorroMN,0)		AS U5C_DESV_OportunidadAhorroMN,
		ISNULL(F.U5C_MIN_RealUUVendidas,0)	AS U5C_MIN_RealUUVendidas,
		ISNULL(F.U5C_MIN_RealUUDevueltas,0)			AS U5C_MIN_RealUUDevueltas,
		ISNULL(F.U5C_MIN_RealUUAnuladas,0)		AS U5C_MIN_RealUUAnuladas,
		ISNULL(F.U5C_MIN_RealVtaMNNeto,0)		AS U5C_MIN_RealVtaMNNeto,
		ISNULL(F.U5C_MIN_OportunidadAhorroMN,0)		AS U5C_MIN_OportunidadAhorroMN,
		ISNULL(F.U5C_MAX_RealUUVendidas,0)		AS U5C_MAX_RealUUVendidas,
		ISNULL(F.U5C_MAX_RealUUDevueltas,0)		AS U5C_MAX_RealUUDevueltas,
		ISNULL(F.U5C_MAX_RealUUAnuladas,0)		AS U5C_MAX_RealUUAnuladas,
		ISNULL(F.U5C_MAX_RealVtaMNNeto,0)		AS U5C_MAX_RealVtaMNNeto,
		ISNULL(E.U6C_MAX_OportunidadAhorroMN,0) AS U6C_MAX_OportunidadAhorroMN,
		ISNULL(E.U6C_PRO_RealVtaMNNeto,0) AS U6C_PRO_RealVtaMNNeto,
		ISNULL(E.U6C_PRO_OportunidadAhorroMN,0)		AS U6C_PRO_OportunidadAhorroMN,
		ISNULL(E.U6C_DESV_RealUUVendidas,0)	AS U6C_DESV_RealUUVendidas,
		ISNULL(E.U6C_DESV_RealUUDevueltas,0)		AS U6C_DESV_RealUUDevueltas,
		ISNULL(E.U6C_DESV_RealUUAnuladas,0)		AS U6C_DESV_RealUUAnuladas,
		ISNULL(E.U6C_DESV_RealVtaMNNeto,0)		AS U6C_DESV_RealVtaMNNeto,
		ISNULL(E.U6C_DESV_OportunidadAhorroMN,0)		AS U6C_DESV_OportunidadAhorroMN,
		ISNULL(E.U6C_MIN_RealUUVendidas,0)	AS U6C_MIN_RealUUVendidas,
		ISNULL(E.U6C_MIN_RealUUDevueltas,0)			AS U6C_MIN_RealUUDevueltas,
		ISNULL(E.U6C_MIN_RealUUAnuladas,0)		AS U6C_MIN_RealUUAnuladas,
		ISNULL(E.U6C_MIN_RealVtaMNNeto,0)		AS U6C_MIN_RealVtaMNNeto,
		ISNULL(E.U6C_MIN_OportunidadAhorroMN,0)		AS U6C_MIN_OportunidadAhorroMN,
		ISNULL(E.U6C_MAX_RealUUVendidas,0)	AS U6C_MAX_RealUUVendidas,
		ISNULL(E.U6C_MAX_RealUUDevueltas,0)			AS U6C_MAX_RealUUDevueltas,
		ISNULL(E.U6C_MAX_RealUUAnuladas,0)		AS U6C_MAX_RealUUAnuladas,
		ISNULL(E.U6C_MAX_RealVtaMNNeto,0)		AS U6C_MAX_RealVtaMNNeto,
		ISNULL(D.U9C_MAX_OportunidadAhorroMN,0) AS U9C_MAX_OportunidadAhorroMN,
		ISNULL(D.U9C_PRO_RealVtaMNNeto,0) AS U9C_PRO_RealVtaMNNeto,
		ISNULL(D.U9C_PRO_OportunidadAhorroMN,0)		AS U9C_PRO_OportunidadAhorroMN,
		ISNULL(D.U9C_DESV_RealUUVendidas,0)	AS U9C_DESV_RealUUVendidas,
		ISNULL(D.U9C_DESV_RealUUDevueltas,0)		AS U9C_DESV_RealUUDevueltas,
		ISNULL(D.U9C_DESV_RealUUAnuladas,0)		AS U9C_DESV_RealUUAnuladas,
		ISNULL(D.U9C_DESV_RealVtaMNNeto,0)			AS U9C_DESV_RealVtaMNNeto,
		ISNULL(D.U9C_DESV_OportunidadAhorroMN,0)		AS U9C_DESV_OportunidadAhorroMN,
		ISNULL(D.U9C_MIN_RealUUVendidas,0)	AS U9C_MIN_RealUUVendidas,
		ISNULL(D.U9C_MIN_RealUUDevueltas,0)			AS U9C_MIN_RealUUDevueltas,
		ISNULL(D.U9C_MIN_RealUUAnuladas,0)		AS U9C_MIN_RealUUAnuladas,
		ISNULL(D.U9C_MIN_RealVtaMNNeto,0)		AS U9C_MIN_RealVtaMNNeto,
		ISNULL(D.U9C_MIN_OportunidadAhorroMN,0)		AS U9C_MIN_OportunidadAhorroMN,
		ISNULL(D.U9C_MAX_RealUUVendidas,0)	AS U9C_MAX_RealUUVendidas,
		ISNULL(D.U9C_MAX_RealUUDevueltas,0)			AS U9C_MAX_RealUUDevueltas,
		ISNULL(D.U9C_MAX_RealUUAnuladas,0)		AS U9C_MAX_RealUUAnuladas,
		ISNULL(D.U9C_MAX_RealVtaMNNeto,0)		AS U9C_MAX_RealVtaMNNeto,
		ISNULL(C.U12C_MAX_OportunidadAhorroMN,0) AS U12C_MAX_OportunidadAhorroMN,
		ISNULL(C.U12C_PRO_RealVtaMNNeto,0) AS U12C_PRO_RealVtaMNNeto,
		ISNULL(C.U12C_PRO_OportunidadAhorroMN,0)		AS U12C_PRO_OportunidadAhorroMN,
		ISNULL(C.U12C_DESV_RealUUVendidas,0)	AS U12C_DESV_RealUUVendidas,
		ISNULL(C.U12C_DESV_RealUUDevueltas,0)		AS U12C_DESV_RealUUDevueltas,
		ISNULL(C.U12C_DESV_RealUUAnuladas,0)		AS U12C_DESV_RealUUAnuladas,
		ISNULL(C.U12C_DESV_RealVtaMNNeto,0)		AS U12C_DESV_RealVtaMNNeto,
		ISNULL(C.U12C_DESV_OportunidadAhorroMN,0)		AS U12C_DESV_OportunidadAhorroMN,
		ISNULL(C.U12C_MIN_RealUUVendidas,0)	AS U12C_MIN_RealUUVendidas,
		ISNULL(C.U12C_MIN_RealUUDevueltas,0)		AS U12C_MIN_RealUUDevueltas,
		ISNULL(C.U12C_MIN_RealUUAnuladas,0)		AS U12C_MIN_RealUUAnuladas,
		ISNULL(C.U12C_MIN_RealVtaMNNeto,0)		AS U12C_MIN_RealVtaMNNeto,
		ISNULL(C.U12C_MIN_OportunidadAhorroMN,0)		AS U12C_MIN_OportunidadAhorroMN,
		ISNULL(C.U12C_MAX_RealUUVendidas,0)	AS U12C_MAX_RealUUVendidas,
		ISNULL(C.U12C_MAX_RealUUDevueltas,0)		AS U12C_MAX_RealUUDevueltas,
		ISNULL(C.U12C_MAX_RealUUAnuladas,0)		AS U12C_MAX_RealUUAnuladas,
		ISNULL(C.U12C_MAX_RealVtaMNNeto,0)		AS U12C_MAX_RealVtaMNNeto,
		ISNULL(B.U15C_MAX_OportunidadAhorroMN,0) AS U15C_MAX_OportunidadAhorroMN,
		ISNULL(B.U15C_PRO_RealVtaMNNeto,0) AS U15C_PRO_RealVtaMNNeto,
		ISNULL(B.U15C_PRO_OportunidadAhorroMN,0)		AS U15C_PRO_OportunidadAhorroMN,
		ISNULL(B.U15C_DESV_RealUUVendidas,0)	AS U15C_DESV_RealUUVendidas,
		ISNULL(B.U15C_DESV_RealUUDevueltas,0)		AS U15C_DESV_RealUUDevueltas,
		ISNULL(B.U15C_DESV_RealUUAnuladas,0)		AS U15C_DESV_RealUUAnuladas,
		ISNULL(B.U15C_DESV_RealVtaMNNeto,0)		AS U15C_DESV_RealVtaMNNeto,
		ISNULL(B.U15C_DESV_OportunidadAhorroMN,0)		AS U15C_DESV_OportunidadAhorroMN,
		ISNULL(B.U15C_MIN_RealUUVendidas,0)	AS U15C_MIN_RealUUVendidas,
		ISNULL(B.U15C_MIN_RealUUDevueltas,0)		AS U15C_MIN_RealUUDevueltas,
		ISNULL(B.U15C_MIN_RealUUAnuladas,0)		AS U15C_MIN_RealUUAnuladas,
		ISNULL(B.U15C_MIN_RealVtaMNNeto,0)		AS U15C_MIN_RealVtaMNNeto,
		ISNULL(B.U15C_MIN_OportunidadAhorroMN,0)		AS U15C_MIN_OportunidadAhorroMN,
		ISNULL(B.U15C_MAX_RealUUVendidas,0)	AS U15C_MAX_RealUUVendidas,
		ISNULL(B.U15C_MAX_RealUUDevueltas,0)		AS U15C_MAX_RealUUDevueltas,
		ISNULL(B.U15C_MAX_RealUUAnuladas,0)		AS U15C_MAX_RealUUAnuladas,
		ISNULL(B.U15C_MAX_RealVtaMNNeto,0)		AS U15C_MAX_RealVtaMNNeto,
		ISNULL(A.U18C_MAX_OportunidadAhorroMN,0) AS U18C_MAX_OportunidadAhorroMN,
		ISNULL(A.U18C_PRO_RealVtaMNNeto,0) AS U18C_PRO_RealVtaMNNeto,
		ISNULL(A.U18C_PRO_OportunidadAhorroMN,0)		AS U18C_PRO_OportunidadAhorroMN,
		ISNULL(A.U18C_DESV_RealUUVendidas,0)	AS U18C_DESV_RealUUVendidas,
		ISNULL(A.U18C_DESV_RealUUDevueltas,0)		AS U18C_DESV_RealUUDevueltas,
		ISNULL(A.U18C_DESV_RealUUAnuladas,0)		AS U18C_DESV_RealUUAnuladas,
		ISNULL(A.U18C_DESV_RealVtaMNNeto,0)		AS U18C_DESV_RealVtaMNNeto,
		ISNULL(A.U18C_DESV_OportunidadAhorroMN,0)		AS U18C_DESV_OportunidadAhorroMN,
		ISNULL(A.U18C_MIN_RealUUVendidas,0)	AS U18C_MIN_RealUUVendidas,
		ISNULL(A.U18C_MIN_RealUUDevueltas,0)		AS U18C_MIN_RealUUDevueltas,
		ISNULL(A.U18C_MIN_RealUUAnuladas,0)		AS U18C_MIN_RealUUAnuladas,
		ISNULL(A.U18C_MIN_RealVtaMNNeto,0)		AS U18C_MIN_RealVtaMNNeto,
		ISNULL(A.U18C_MIN_OportunidadAhorroMN,0)		AS U18C_MIN_OportunidadAhorroMN,
		ISNULL(A.U18C_MAX_RealUUVendidas,0)	AS U18C_MAX_RealUUVendidas,
		ISNULL(A.U18C_MAX_RealUUDevueltas,0)		AS U18C_MAX_RealUUDevueltas,
		ISNULL(A.U18C_MAX_RealUUAnuladas,0)		AS U18C_MAX_RealUUAnuladas,
		ISNULL(A.U18C_MAX_RealVtaMNNeto,0)		AS U18C_MAX_RealVtaMNNeto,
		ISNULL(U2C_RealUUVendidas_SUC,0)			AS U2C_RealUUVendidas_SUC,			
		ISNULL(U2C_OportunidadAhorroMN_SUC,	0)	AS U2C_OportunidadAhorroMN_SUC,		
		ISNULL(U2C_RealVtaMNNeto_SUC,0)			AS U2C_RealVtaMNNeto_SUC,			
		ISNULL(U3C_RealUUVendidas_SUC,	0)		AS U3C_RealUUVendidas_SUC,			
		ISNULL(U3C_OportunidadAhorroMN_SUC,	0)	AS U3C_OportunidadAhorroMN_SUC,		
		ISNULL(U3C_RealVtaMNNeto_SUC,	0)		AS U3C_RealVtaMNNeto_SUC,			
		ISNULL(U4C_RealUUVendidas_SUC,	0)		AS U4C_RealUUVendidas_SUC,			
		ISNULL(U4C_OportunidadAhorroMN_SUC,	0)	AS U4C_OportunidadAhorroMN_SUC,		
		ISNULL(U4C_RealVtaMNNeto_SUC,0)			AS U4C_RealVtaMNNeto_SUC,			
		ISNULL(U5C_RealUUVendidas_SUC,	0)		AS U5C_RealUUVendidas_SUC,			
		ISNULL(U5C_OportunidadAhorroMN_SUC,	0)	AS U5C_OportunidadAhorroMN_SUC,		
		ISNULL(U5C_RealVtaMNNeto_SUC,0)			AS U5C_RealVtaMNNeto_SUC,			
		ISNULL(U6C_RealUUVendidas_SUC,	0)		AS U6C_RealUUVendidas_SUC,			
		ISNULL(U6C_OportunidadAhorroMN_SUC,0)		AS U6C_OportunidadAhorroMN_SUC,		
		ISNULL(U6C_RealVtaMNNeto_SUC,	0)		AS U6C_RealVtaMNNeto_SUC,			
		ISNULL(U3C_RealUUVendidas_II,	0)		AS U3C_RealUUVendidas_II,			
		ISNULL(U3C_OportunidadAhorroMN_II,	0)	AS U3C_OportunidadAhorroMN_II,		
		ISNULL(U3C_RealVtaMNNeto_II,	0)		AS U3C_RealVtaMNNeto_II,			
		ISNULL(U9C_RealUUVendidas_SUC,	0)		AS U9C_RealUUVendidas_SUC,			
		ISNULL(U9C_OportunidadAhorroMN_SUC,0)		AS U9C_OportunidadAhorroMN_SUC,		
		ISNULL(U9C_RealVtaMNNeto_SUC,	0)		AS U9C_RealVtaMNNeto_SUC,			
		ISNULL(U3C_RealUUVendidas_SUC_III,	0)	AS U3C_RealUUVendidas_SUC_III,		
		ISNULL(U3C_OportunidadAhorroMN_SUC_III,0)	AS U3C_OportunidadAhorroMN_SUC_III,	
		ISNULL(U3C_RealVtaMNNeto_SUC_III,0)		AS U3C_RealVtaMNNeto_SUC_III,		
		ISNULL(U12C_RealUUVendidas_SUC,	0)		AS U12C_RealUUVendidas_SUC,			
		ISNULL(U12C_OportunidadAhorroMN_SUC,0)	AS U12C_OportunidadAhorroMN_SUC,	
		ISNULL(U12C_RealVtaMNNeto_SUC,	0)		AS U12C_RealVtaMNNeto_SUC,			
		ISNULL(U6C_RealUUVendidas_SUCIV,0)		AS U6C_RealUUVendidas_SUCIV,		
		ISNULL(U6C_OportunidadAhorroMN_SUCIV,0)	AS U6C_OportunidadAhorroMN_SUCIV,	
		ISNULL(U6C_RealVtaMNNeto_SUCIV,	0)		AS U6C_RealVtaMNNeto_SUCIV,			
		ISNULL(U15C_RealUUVendidas_SUC,	0)		AS U15C_RealUUVendidas_SUC,			
		ISNULL(U15C_OportunidadAhorroMN_SUC,0)	AS U15C_OportunidadAhorroMN_SUC,	
		ISNULL(U15C_RealVtaMNNeto_SUC,	0)		AS U15C_RealVtaMNNeto_SUC,			
		ISNULL(U9C_RealUUVendidas_V,	0)		AS U9C_RealUUVendidas_V,			
		ISNULL(U9C_OportunidadAhorroMN_V,0)		AS U9C_OportunidadAhorroMN_V,		
		ISNULL(U9C_RealVtaMNNeto_V,		0)		AS U9C_RealVtaMNNeto_V,				
		ISNULL(U18C_RealUUVendidas_SUC,0)			AS U18C_RealUUVendidas_SUC,			
		ISNULL(U18C_OportunidadAhorroMN_SUC,0)	AS U18C_OportunidadAhorroMN_SUC,	
		ISNULL(U18C_RealVtaMNNeto_SUC,	0)		AS U18C_RealVtaMNNeto_SUC,			
		ISNULL(U12C_RealUUVendidas_VI,	0)		AS U12C_RealUUVendidas_VI,			
		ISNULL(U12C_OportunidadAhorroMN_VI,	0)	AS U12C_OportunidadAhorroMN_VI,		
		ISNULL(U12C_RealVtaMNNeto_VI,	0)		AS U12C_RealVtaMNNeto_VI
INTO #KR_VEN_CAMP_TOT
FROM EbelistaCampanaMenos17 A
LEFT JOIN EbelistaCampanaMenos14 B ON A.Pkebelista = B.Pkebelista AND A.CodPais = B.CodPais
LEFT JOIN EbelistaCampanaMenos11 C ON A.Pkebelista = C.Pkebelista AND A.CodPais = C.CodPais
LEFT JOIN EbelistaCampanaMenos8 D ON A.Pkebelista = D.Pkebelista AND A.CodPais = D.CodPais
LEFT JOIN EbelistaCampanaMenos5 E ON A.Pkebelista = E.Pkebelista AND A.CodPais = E.CodPais
LEFT JOIN EbelistaCampanaMenos4 F ON A.Pkebelista = F.Pkebelista AND A.CodPais = F.CodPais
LEFT JOIN EbelistaCampanaMenos3 G ON A.Pkebelista = G.Pkebelista AND A.CodPais = G.CodPais
LEFT JOIN EbelistaCampanaMenos2 H ON A.Pkebelista = H.Pkebelista AND A.CodPais = H.CodPais 
LEFT JOIN EbelistaCampanaMenos1 I ON A.Pkebelista = I.Pkebelista AND A.CodPais = I.CodPais
LEFT JOIN EbelistaUC J ON A.Pkebelista = J.Pkebelista AND A.CodPais = J.CodPais

/*PE: 9min aprox a las 2pm Cantidad: 272854 Consultoras al dia siguiente 2 min a las 9:19*/

--select * from BD_ANALITICO.dbo.KR_MAT_FUGA_201716
--WHERE PkEbelista = 1228448

--select * from #TMP_EbeHistoria
--WHERE PkEbelista = 1228448

IF OBJECT_ID ('tempdb..#KR_TARGET_FUGA1') IS NOT NULL DROP TABLE #KR_TARGET_FUGA1

CREATE TABLE #KR_TARGET_FUGA1
(
	AnioCampanaT CHAR(6),
	AnioCampanaUC CHAR(6),
	CodPais CHAR(2),
	[Target] INT,
	PKEbelista INT,
	Tipo VARCHAR(12),
	Cx_Status VARCHAR(15),
	Cx1_Status VARCHAR(15),
	Cx2_Status VARCHAR(15),
	Cx_Activa tinyint,
	Cx1_Activa tinyint,
	Cx2_Activa tinyint,
	Cx_Comp_Rolling VARCHAR(20),
	Cx1_Comp_Rolling VARCHAR(20),
	Cx2_Comp_Rolling VARCHAR(20),
	Cx_PasoPedido tinyint,
	Cx1_PasoPedido tinyint,
	Cx2_PasoPedido tinyint,
)

INSERT INTO #KR_TARGET_FUGA1
EXEC KR_MATRIZ_TARG_V1 @CodPais,@AnioCampana


IF OBJECT_ID('tempdb..#KR_VEN_CAMP_TF') IS NOT NULL DROP TABLE #KR_VEN_CAMP_TF

SELECT 
B.[TARGET],
B.PKEBELISTA,
B.ANIOCAMPANAUC AS ANIOCAMPANA,
CASE WHEN B.TIPO='nuevas' THEN 1  WHEN B.TIPO='Establecidas' THEN 0 END AS T_NUEVA,
ISNULL(A.UC_RealUUVendidas,0) AS UC_RealUUVendidas,
ISNULL(A.U2C_RealUUVendidas,0) AS U2C_RealUUVendidas,
ISNULL(A.U3C_RealUUVendidas,0) AS U3C_RealUUVendidas,
ISNULL(A.U4C_RealUUVendidas,0) AS U4C_RealUUVendidas,
ISNULL(A.U5C_RealUUVendidas,0) AS U5C_RealUUVendidas,
ISNULL(A.U6C_RealUUVendidas,0) AS U6C_RealUUVendidas,
ISNULL(A.U9C_RealUUVendidas,0) AS U9C_RealUUVendidas,
ISNULL(A.U12C_RealUUVendidas,0) AS U12C_RealUUVendidas,
ISNULL(A.U15C_RealUUVendidas,0) AS U15C_RealUUVendidas,
ISNULL(A.U18C_RealUUVendidas,0) AS U18C_RealUUVendidas,
ISNULL(A.UC_RealUUFaltantes,0) AS UC_RealUUFaltantes,
ISNULL(A.U2C_RealUUFaltantes,0) AS U2C_RealUUFaltantes,
ISNULL(A.U3C_RealUUFaltantes,0) AS U3C_RealUUFaltantes,
ISNULL(A.U4C_RealUUFaltantes,0) AS U4C_RealUUFaltantes,
ISNULL(A.U5C_RealUUFaltantes,0) AS U5C_RealUUFaltantes,
ISNULL(A.U6C_RealUUFaltantes,0) AS U6C_RealUUFaltantes,
ISNULL(A.U9C_RealUUFaltantes,0) AS U9C_RealUUFaltantes,
ISNULL(A.U12C_RealUUFaltantes,0) AS U12C_RealUUFaltantes,
ISNULL(A.U15C_RealUUFaltantes,0) AS U15C_RealUUFaltantes,
ISNULL(A.U18C_RealUUFaltantes,0) AS U18C_RealUUFaltantes,
ISNULL(A.UC_RealUUDevueltas,0) AS UC_RealUUDevueltas,
ISNULL(A.U2C_RealUUDevueltas,0) AS U2C_RealUUDevueltas,
ISNULL(A.U3C_RealUUDevueltas,0) AS U3C_RealUUDevueltas,
ISNULL(A.U4C_RealUUDevueltas,0) AS U4C_RealUUDevueltas,
ISNULL(A.U5C_RealUUDevueltas,0) AS U5C_RealUUDevueltas,
ISNULL(A.U6C_RealUUDevueltas,0) AS U6C_RealUUDevueltas,
ISNULL(A.U9C_RealUUDevueltas,0) AS U9C_RealUUDevueltas,
ISNULL(A.U12C_RealUUDevueltas,0) AS U12C_RealUUDevueltas,
ISNULL(A.U15C_RealUUDevueltas,0) AS U15C_RealUUDevueltas,
ISNULL(A.U18C_RealUUDevueltas,0) AS U18C_RealUUDevueltas,
ISNULL(A.UC_RealUUAnuladas,0) AS UC_RealUUAnuladas,
ISNULL(A.U2C_RealUUAnuladas,0) AS U2C_RealUUAnuladas,
ISNULL(A.U3C_RealUUAnuladas,0) AS U3C_RealUUAnuladas,
ISNULL(A.U4C_RealUUAnuladas,0) AS U4C_RealUUAnuladas,
ISNULL(A.U5C_RealUUAnuladas,0) AS U5C_RealUUAnuladas,
ISNULL(A.U6C_RealUUAnuladas,0) AS U6C_RealUUAnuladas,
ISNULL(A.U9C_RealUUAnuladas,0) AS U9C_RealUUAnuladas,
ISNULL(A.U12C_RealUUAnuladas,0) AS U12C_RealUUAnuladas,
ISNULL(A.U15C_RealUUAnuladas,0) AS U15C_RealUUAnuladas,
ISNULL(A.U18C_RealUUAnuladas,0) AS U18C_RealUUAnuladas,
ISNULL(A.UC_RealVtaMNNeto,0) AS UC_RealVtaMNNeto,
ISNULL(A.U2C_RealVtaMNNeto,0) AS U2C_RealVtaMNNeto,
ISNULL(A.U3C_RealVtaMNNeto,0) AS U3C_RealVtaMNNeto,
ISNULL(A.U4C_RealVtaMNNeto,0) AS U4C_RealVtaMNNeto,
ISNULL(A.U5C_RealVtaMNNeto,0) AS U5C_RealVtaMNNeto,
ISNULL(A.U6C_RealVtaMNNeto,0) AS U6C_RealVtaMNNeto,
ISNULL(A.U9C_RealVtaMNNeto,0) AS U9C_RealVtaMNNeto,
ISNULL(A.U12C_RealVtaMNNeto,0) AS U12C_RealVtaMNNeto,
ISNULL(A.U15C_RealVtaMNNeto,0) AS U15C_RealVtaMNNeto,
ISNULL(A.U18C_RealVtaMNNeto,0) AS U18C_RealVtaMNNeto,
ISNULL(A.UC_OportunidadAhorroMN,0) AS UC_OportunidadAhorroMN,
ISNULL(A.U2C_OportunidadAhorroMN,0) AS U2C_OportunidadAhorroMN,
ISNULL(A.U3C_OportunidadAhorroMN,0) AS U3C_OportunidadAhorroMN,
ISNULL(A.U4C_OportunidadAhorroMN,0) AS U4C_OportunidadAhorroMN,
ISNULL(A.U5C_OportunidadAhorroMN,0) AS U5C_OportunidadAhorroMN,
ISNULL(A.U6C_OportunidadAhorroMN,0) AS U6C_OportunidadAhorroMN,
ISNULL(A.U9C_OportunidadAhorroMN,0) AS U9C_OportunidadAhorroMN,
ISNULL(A.U12C_OportunidadAhorroMN,0) AS U12C_OportunidadAhorroMN,
ISNULL(A.U15C_OportunidadAhorroMN,0) AS U15C_OportunidadAhorroMN,
ISNULL(A.U18C_OportunidadAhorroMN,0) AS U18C_OportunidadAhorroMN,
--
ISNULL(A.U2C_PRO_RealVtaMNNeto,0) as U2C_PRO_RealVtaMNNeto,
ISNULL(A.U2C_PRO_OportunidadAhorroMN,0) as U2C_PRO_OportunidadAhorroMN,
ISNULL(A.U2C_DESV_RealUUVendidas,0) AS U2C_DESV_RealUUVendidas,
ISNULL(A.U2C_DESV_RealUUDevueltas,0) AS U2C_DESV_RealUUDevueltas,
ISNULL(A.U2C_DESV_RealUUAnuladas,0) AS U2C_DESV_RealUUAnuladas,
ISNULL(A.U2C_DESV_RealVtaMNNeto,0) AS U2C_DESV_RealVtaMNNeto,
ISNULL(A.U2C_MIN_RealUUVendidas,0) AS U2C_MIN_RealUUVendidas,
ISNULL(A.U2C_MIN_RealUUDevueltas,0) AS U2C_MIN_RealUUDevueltas,
ISNULL(A.U2C_MIN_RealUUAnuladas,0) AS U2C_MIN_RealUUAnuladas,
ISNULL(A.U2C_MIN_RealVtaMNNeto,0) AS U2C_MIN_RealVtaMNNeto,
ISNULL(A.U2C_MAX_RealUUVendidas,0) AS U2C_MAX_RealUUVendidas,
ISNULL(A.U2C_MAX_RealUUDevueltas,0) AS U2C_MAX_RealUUDevueltas,
ISNULL(A.U2C_MAX_RealUUAnuladas,0) AS U2C_MAX_RealUUAnuladas,
ISNULL(A.U2C_MAX_RealVtaMNNeto,0) AS U2C_MAX_RealVtaMNNeto,
ISNULL(A.U3C_PRO_RealVtaMNNeto,0) as U3C_PRO_RealVtaMNNeto,
ISNULL(A.U3C_PRO_OportunidadAhorroMN,0) as U3C_PRO_OportunidadAhorroMN,
ISNULL(A.U3C_DESV_RealUUVendidas,0) AS U3C_DESV_RealUUVendidas,
ISNULL(A.U3C_DESV_RealUUDevueltas,0) AS U3C_DESV_RealUUDevueltas,
ISNULL(A.U3C_DESV_RealUUAnuladas,0) AS U3C_DESV_RealUUAnuladas,
ISNULL(A.U3C_DESV_RealVtaMNNeto,0) AS U3C_DESV_RealVtaMNNeto,
ISNULL(A.U3C_MIN_RealUUVendidas,0) AS U3C_MIN_RealUUVendidas,
ISNULL(A.U3C_MIN_RealUUDevueltas,0) AS U3C_MIN_RealUUDevueltas,
ISNULL(A.U3C_MIN_RealUUAnuladas,0) AS U3C_MIN_RealUUAnuladas,
ISNULL(A.U3C_MIN_RealVtaMNNeto,0) AS U3C_MIN_RealVtaMNNeto,
ISNULL(A.U3C_MAX_RealUUVendidas,0) AS U3C_MAX_RealUUVendidas,
ISNULL(A.U3C_MAX_RealUUDevueltas,0) AS U3C_MAX_RealUUDevueltas,
ISNULL(A.U3C_MAX_RealUUAnuladas,0) AS U3C_MAX_RealUUAnuladas,
ISNULL(A.U3C_MAX_RealVtaMNNeto,0) AS U3C_MAX_RealVtaMNNeto,
ISNULL(A.U4C_PRO_RealVtaMNNeto,0) as U4C_PRO_RealVtaMNNeto,
ISNULL(A.U4C_PRO_OportunidadAhorroMN,0) as U4C_PRO_OportunidadAhorroMN,
ISNULL(A.U4C_DESV_RealUUVendidas,0) AS U4C_DESV_RealUUVendidas,
ISNULL(A.U4C_DESV_RealUUDevueltas,0) AS U4C_DESV_RealUUDevueltas,
ISNULL(A.U4C_DESV_RealUUAnuladas,0) AS U4C_DESV_RealUUAnuladas,
ISNULL(A.U4C_DESV_RealVtaMNNeto,0) AS U4C_DESV_RealVtaMNNeto,
ISNULL(A.U4C_MIN_RealUUVendidas,0) AS U4C_MIN_RealUUVendidas,
ISNULL(A.U4C_MIN_RealUUDevueltas,0) AS U4C_MIN_RealUUDevueltas,
ISNULL(A.U4C_MIN_RealUUAnuladas,0) AS U4C_MIN_RealUUAnuladas,
ISNULL(A.U4C_MIN_RealVtaMNNeto,0) AS U4C_MIN_RealVtaMNNeto,
ISNULL(A.U4C_MAX_RealUUVendidas,0) AS U4C_MAX_RealUUVendidas,
ISNULL(A.U4C_MAX_RealUUDevueltas,0) AS U4C_MAX_RealUUDevueltas,
ISNULL(A.U4C_MAX_RealUUAnuladas,0) AS U4C_MAX_RealUUAnuladas,
ISNULL(A.U4C_MAX_RealVtaMNNeto,0) AS U4C_MAX_RealVtaMNNeto,
ISNULL(A.U5C_PRO_RealVtaMNNeto,0) as U5C_PRO_RealVtaMNNeto,
ISNULL(A.U5C_PRO_OportunidadAhorroMN,0) as U5C_PRO_OportunidadAhorroMN,
ISNULL(A.U5C_DESV_RealUUVendidas,0) AS U5C_DESV_RealUUVendidas,
ISNULL(A.U5C_DESV_RealUUDevueltas,0) AS U5C_DESV_RealUUDevueltas,
ISNULL(A.U5C_DESV_RealUUAnuladas,0) AS U5C_DESV_RealUUAnuladas,
ISNULL(A.U5C_DESV_RealVtaMNNeto,0) AS U5C_DESV_RealVtaMNNeto,
ISNULL(A.U5C_MIN_RealUUVendidas,0) AS U5C_MIN_RealUUVendidas,
ISNULL(A.U5C_MIN_RealUUDevueltas,0) AS U5C_MIN_RealUUDevueltas,
ISNULL(A.U5C_MIN_RealUUAnuladas,0) AS U5C_MIN_RealUUAnuladas,
ISNULL(A.U5C_MIN_RealVtaMNNeto,0) AS U5C_MIN_RealVtaMNNeto,
ISNULL(A.U5C_MAX_RealUUVendidas,0) AS U5C_MAX_RealUUVendidas,
ISNULL(A.U5C_MAX_RealUUDevueltas,0) AS U5C_MAX_RealUUDevueltas,
ISNULL(A.U5C_MAX_RealUUAnuladas,0) AS U5C_MAX_RealUUAnuladas,
ISNULL(A.U5C_MAX_RealVtaMNNeto,0) AS U5C_MAX_RealVtaMNNeto,
ISNULL(A.U6C_PRO_RealVtaMNNeto,0) as U6C_PRO_RealVtaMNNeto,
ISNULL(A.U6C_PRO_OportunidadAhorroMN,0) as U6C_PRO_OportunidadAhorroMN,
ISNULL(A.U6C_DESV_RealUUVendidas,0) AS U6C_DESV_RealUUVendidas,
ISNULL(A.U6C_DESV_RealUUDevueltas,0) AS U6C_DESV_RealUUDevueltas,
ISNULL(A.U6C_DESV_RealUUAnuladas,0) AS U6C_DESV_RealUUAnuladas,
ISNULL(A.U6C_DESV_RealVtaMNNeto,0) AS U6C_DESV_RealVtaMNNeto,
ISNULL(A.U6C_MIN_RealUUVendidas,0) AS U6C_MIN_RealUUVendidas,
ISNULL(A.U6C_MIN_RealUUDevueltas,0) AS U6C_MIN_RealUUDevueltas,
ISNULL(A.U6C_MIN_RealUUAnuladas,0) AS U6C_MIN_RealUUAnuladas,
ISNULL(A.U6C_MIN_RealVtaMNNeto,0) AS U6C_MIN_RealVtaMNNeto,
ISNULL(A.U6C_MAX_RealUUVendidas,0) AS U6C_MAX_RealUUVendidas,
ISNULL(A.U6C_MAX_RealUUDevueltas,0) AS U6C_MAX_RealUUDevueltas,
ISNULL(A.U6C_MAX_RealUUAnuladas,0) AS U6C_MAX_RealUUAnuladas,
ISNULL(A.U6C_MAX_RealVtaMNNeto,0) AS U6C_MAX_RealVtaMNNeto,
ISNULL(A.U9C_PRO_RealVtaMNNeto,0) as U9C_PRO_RealVtaMNNeto,
ISNULL(A.U9C_PRO_OportunidadAhorroMN,0) as U9C_PRO_OportunidadAhorroMN,
ISNULL(A.U9C_DESV_RealUUVendidas,0) AS U9C_DESV_RealUUVendidas,
ISNULL(A.U9C_DESV_RealUUDevueltas,0) AS U9C_DESV_RealUUDevueltas,
ISNULL(A.U9C_DESV_RealUUAnuladas,0) AS U9C_DESV_RealUUAnuladas,
ISNULL(A.U9C_DESV_RealVtaMNNeto,0) AS U9C_DESV_RealVtaMNNeto,
ISNULL(A.U9C_MIN_RealUUVendidas,0) AS U9C_MIN_RealUUVendidas,
ISNULL(A.U9C_MIN_RealUUDevueltas,0) AS U9C_MIN_RealUUDevueltas,
ISNULL(A.U9C_MIN_RealUUAnuladas,0) AS U9C_MIN_RealUUAnuladas,
ISNULL(A.U9C_MIN_RealVtaMNNeto,0) AS U9C_MIN_RealVtaMNNeto,
ISNULL(A.U9C_MAX_RealUUVendidas,0) AS U9C_MAX_RealUUVendidas,
ISNULL(A.U9C_MAX_RealUUDevueltas,0) AS U9C_MAX_RealUUDevueltas,
ISNULL(A.U9C_MAX_RealUUAnuladas,0) AS U9C_MAX_RealUUAnuladas,
ISNULL(A.U9C_MAX_RealVtaMNNeto,0) AS U9C_MAX_RealVtaMNNeto,
ISNULL(A.U12C_PRO_RealVtaMNNeto,0) as U12C_PRO_RealVtaMNNeto,
ISNULL(A.U12C_PRO_OportunidadAhorroMN,0) as U12C_PRO_OportunidadAhorroMN,
ISNULL(A.U12C_DESV_RealUUVendidas,0) AS U12C_DESV_RealUUVendidas,
ISNULL(A.U12C_DESV_RealUUDevueltas,0) AS U12C_DESV_RealUUDevueltas,
ISNULL(A.U12C_DESV_RealUUAnuladas,0) AS U12C_DESV_RealUUAnuladas,
ISNULL(A.U12C_DESV_RealVtaMNNeto,0) AS U12C_DESV_RealVtaMNNeto,
ISNULL(A.U12C_MIN_RealUUVendidas,0) AS U12C_MIN_RealUUVendidas,
ISNULL(A.U12C_MIN_RealUUDevueltas,0) AS U12C_MIN_RealUUDevueltas,
ISNULL(A.U12C_MIN_RealUUAnuladas,0) AS U12C_MIN_RealUUAnuladas,
ISNULL(A.U12C_MIN_RealVtaMNNeto,0) AS U12C_MIN_RealVtaMNNeto,
ISNULL(A.U12C_MAX_RealUUVendidas,0) AS U12C_MAX_RealUUVendidas,
ISNULL(A.U12C_MAX_RealUUDevueltas,0) AS U12C_MAX_RealUUDevueltas,
ISNULL(A.U12C_MAX_RealUUAnuladas,0) AS U12C_MAX_RealUUAnuladas,
ISNULL(A.U12C_MAX_RealVtaMNNeto,0) AS U12C_MAX_RealVtaMNNeto,
ISNULL(A.U15C_PRO_RealVtaMNNeto,0) as U15C_PRO_RealVtaMNNeto,
ISNULL(A.U15C_PRO_OportunidadAhorroMN,0) as U15C_PRO_OportunidadAhorroMN,
ISNULL(A.U15C_DESV_RealUUVendidas,0) AS U15C_DESV_RealUUVendidas,
ISNULL(A.U15C_DESV_RealUUDevueltas,0) AS U15C_DESV_RealUUDevueltas,
ISNULL(A.U15C_DESV_RealUUAnuladas,0) AS U15C_DESV_RealUUAnuladas,
ISNULL(A.U15C_DESV_RealVtaMNNeto,0) AS U15C_DESV_RealVtaMNNeto,
ISNULL(A.U15C_MIN_RealUUVendidas,0) AS U15C_MIN_RealUUVendidas,
ISNULL(A.U15C_MIN_RealUUDevueltas,0) AS U15C_MIN_RealUUDevueltas,
ISNULL(A.U15C_MIN_RealUUAnuladas,0) AS U15C_MIN_RealUUAnuladas,
ISNULL(A.U15C_MIN_RealVtaMNNeto,0) AS U15C_MIN_RealVtaMNNeto,
ISNULL(A.U15C_MAX_RealUUVendidas,0) AS U15C_MAX_RealUUVendidas,
ISNULL(A.U15C_MAX_RealUUDevueltas,0) AS U15C_MAX_RealUUDevueltas,
ISNULL(A.U15C_MAX_RealUUAnuladas,0) AS U15C_MAX_RealUUAnuladas,
ISNULL(A.U15C_MAX_RealVtaMNNeto,0) AS U15C_MAX_RealVtaMNNeto,
ISNULL(A.U18C_PRO_RealVtaMNNeto,0) as U18C_PRO_RealVtaMNNeto,
ISNULL(A.U18C_PRO_OportunidadAhorroMN,0) as U18C_PRO_OportunidadAhorroMN,
ISNULL(A.U18C_DESV_RealUUVendidas,0) AS U18C_DESV_RealUUVendidas,
ISNULL(A.U18C_DESV_RealUUDevueltas,0) AS U18C_DESV_RealUUDevueltas,
ISNULL(A.U18C_DESV_RealUUAnuladas,0) AS U18C_DESV_RealUUAnuladas,
ISNULL(A.U18C_DESV_RealVtaMNNeto,0) AS U18C_DESV_RealVtaMNNeto,
ISNULL(A.U18C_MIN_RealUUVendidas,0) AS U18C_MIN_RealUUVendidas,
ISNULL(A.U18C_MIN_RealUUDevueltas,0) AS U18C_MIN_RealUUDevueltas,
ISNULL(A.U18C_MIN_RealUUAnuladas,0) AS U18C_MIN_RealUUAnuladas,
ISNULL(A.U18C_MIN_RealVtaMNNeto,0) AS U18C_MIN_RealVtaMNNeto,
ISNULL(A.U18C_MAX_RealUUVendidas,0) AS U18C_MAX_RealUUVendidas,
ISNULL(A.U18C_MAX_RealUUDevueltas,0) AS U18C_MAX_RealUUDevueltas,
ISNULL(A.U18C_MAX_RealUUAnuladas,0) AS U18C_MAX_RealUUAnuladas,
ISNULL(A.U18C_MAX_RealVtaMNNeto,0) AS U18C_MAX_RealVtaMNNeto,
ISNULL(A.U2C_DESV_OportunidadAhorroMN,0) AS U2C_DESV_OportunidadAhorroMN,
ISNULL(A.U2C_MIN_OportunidadAhorroMN,0) AS U2C_MIN_OportunidadAhorroMN,
ISNULL(A.U2C_MAX_OportunidadAhorroMN,0) AS U2C_MAX_OportunidadAhorroMN,
ISNULL(A.U3C_DESV_OportunidadAhorroMN,0) AS U3C_DESV_OportunidadAhorroMN,
ISNULL(A.U3C_MIN_OportunidadAhorroMN,0) AS U3C_MIN_OportunidadAhorroMN,
ISNULL(A.U3C_MAX_OportunidadAhorroMN,0) AS U3C_MAX_OportunidadAhorroMN,
ISNULL(A.U4C_DESV_OportunidadAhorroMN,0) AS U4C_DESV_OportunidadAhorroMN,
ISNULL(A.U4C_MIN_OportunidadAhorroMN,0) AS U4C_MIN_OportunidadAhorroMN,
ISNULL(A.U4C_MAX_OportunidadAhorroMN,0) AS U4C_MAX_OportunidadAhorroMN,
ISNULL(A.U5C_DESV_OportunidadAhorroMN,0) AS U5C_DESV_OportunidadAhorroMN,
ISNULL(A.U5C_MIN_OportunidadAhorroMN,0) AS U5C_MIN_OportunidadAhorroMN,
ISNULL(A.U5C_MAX_OportunidadAhorroMN,0) AS U5C_MAX_OportunidadAhorroMN,
ISNULL(A.U6C_DESV_OportunidadAhorroMN,0) AS U6C_DESV_OportunidadAhorroMN,
ISNULL(A.U6C_MIN_OportunidadAhorroMN,0) AS U6C_MIN_OportunidadAhorroMN,
ISNULL(A.U6C_MAX_OportunidadAhorroMN,0) AS U6C_MAX_OportunidadAhorroMN,
ISNULL(A.U9C_DESV_OportunidadAhorroMN,0) AS U9C_DESV_OportunidadAhorroMN,
ISNULL(A.U9C_MIN_OportunidadAhorroMN,0) AS U9C_MIN_OportunidadAhorroMN,
ISNULL(A.U9C_MAX_OportunidadAhorroMN,0) AS U9C_MAX_OportunidadAhorroMN,
ISNULL(A.U12C_DESV_OportunidadAhorroMN,0) AS U12C_DESV_OportunidadAhorroMN,
ISNULL(A.U12C_MIN_OportunidadAhorroMN,0) AS U12C_MIN_OportunidadAhorroMN,
ISNULL(A.U12C_MAX_OportunidadAhorroMN,0) AS U12C_MAX_OportunidadAhorroMN,
ISNULL(A.U15C_DESV_OportunidadAhorroMN,0) AS U15C_DESV_OportunidadAhorroMN,
ISNULL(A.U15C_MIN_OportunidadAhorroMN,0) AS U15C_MIN_OportunidadAhorroMN,
ISNULL(A.U15C_MAX_OportunidadAhorroMN,0) AS U15C_MAX_OportunidadAhorroMN,
ISNULL(A.U18C_DESV_OportunidadAhorroMN,0) AS U18C_DESV_OportunidadAhorroMN,
ISNULL(A.U18C_MIN_OportunidadAhorroMN,0) AS U18C_MIN_OportunidadAhorroMN,
ISNULL(A.U18C_MAX_OportunidadAhorroMN,0) AS U18C_MAX_OportunidadAhorroMN,
case when UC_RealVtaMNNeto=0  or  UC_RealVtaMNNeto is null  then 0 else 1.0*(UC_OportunidadAhorroMN)/UC_RealVtaMNNeto end as Rat1,
case when U2C_RealVtaMNNeto=0  or  U2C_RealVtaMNNeto is null  then 0 else 1.0*(U2C_OportunidadAhorroMN)/U2C_RealVtaMNNeto end as Rat2,
case when U3C_RealVtaMNNeto=0  or U3C_RealVtaMNNeto  is null  then 0 else 1.0*(U3C_OportunidadAhorroMN)/U3C_RealVtaMNNeto end as Rat3,
case when U4C_RealVtaMNNeto=0  or  U4C_RealVtaMNNeto is null  then 0 else 1.0*(U4C_OportunidadAhorroMN)/U4C_RealVtaMNNeto end as Rat4,
case when U5C_RealVtaMNNeto=0  or  U5C_RealVtaMNNeto is null  then 0 else 1.0*(U5C_OportunidadAhorroMN)/U5C_RealVtaMNNeto end as Rat5,
case when U6C_RealVtaMNNeto=0  or  U6C_RealVtaMNNeto is null  then 0 else 1.0*(U6C_OportunidadAhorroMN)/U6C_RealVtaMNNeto end as Rat6,
case when U9C_RealVtaMNNeto=0  or  U9C_RealVtaMNNeto is null  then 0 else 1.0*(U9C_OportunidadAhorroMN)/U9C_RealVtaMNNeto end as Rat7,
case when U12C_RealVtaMNNeto=0  or  U12C_RealVtaMNNeto is null  then 0 else 1.0*(U12C_OportunidadAhorroMN)/U12C_RealVtaMNNeto end as Rat8,
case when U15C_RealVtaMNNeto=0  or  U15C_RealVtaMNNeto is null  then 0 else 1.0*(U15C_OportunidadAhorroMN)/U15C_RealVtaMNNeto end as Rat9,
case when U18C_RealVtaMNNeto=0  or  U18C_RealVtaMNNeto is null  then 0 else 1.0*(U18C_OportunidadAhorroMN)/U18C_RealVtaMNNeto end as Rat10,
case when U18C_MAX_RealVtaMNNeto=0  or  U18C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U18C_MAX_OportunidadAhorroMN)/U18C_MAX_RealVtaMNNeto end as Rat11,
case when U15C_MAX_RealVtaMNNeto=0  or  U15C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U15C_MAX_OportunidadAhorroMN)/U15C_MAX_RealVtaMNNeto end as Rat12,
case when U12C_MAX_RealVtaMNNeto=0  or  U12C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U12C_MAX_OportunidadAhorroMN)/U12C_MAX_RealVtaMNNeto end as Rat13,
case when U9C_MAX_RealVtaMNNeto=0  or  U9C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U9C_MAX_OportunidadAhorroMN)/U9C_MAX_RealVtaMNNeto end as Rat14,
case when U6C_MAX_RealVtaMNNeto=0  or  U6C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U6C_MAX_OportunidadAhorroMN)/U6C_MAX_RealVtaMNNeto end as Rat15,
case when U5C_MAX_RealVtaMNNeto=0  or  U5C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U5C_MAX_OportunidadAhorroMN)/U5C_MAX_RealVtaMNNeto end as Rat16,
case when U4C_MAX_RealVtaMNNeto=0  or  U4C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U4C_MAX_OportunidadAhorroMN)/U4C_MAX_RealVtaMNNeto end as Rat17,
case when U3C_MAX_RealVtaMNNeto=0  or  U3C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U3C_MAX_OportunidadAhorroMN)/U3C_MAX_RealVtaMNNeto end as Rat18,
case when U2C_MAX_RealVtaMNNeto=0  or  U2C_MAX_RealVtaMNNeto is null  then 0 else 1.0*(U2C_MAX_OportunidadAhorroMN)/U2C_MAX_RealVtaMNNeto end as Rat19,

case when U2C_PRO_RealVtaMNNeto=0 or U2C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U2C_PRO_OportunidadAhorroMN)/U2C_PRO_RealVtaMNNeto end as Rat20,
case when U3C_PRO_RealVtaMNNeto=0 or U3C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U3C_PRO_OportunidadAhorroMN)/U3C_PRO_RealVtaMNNeto end as Rat21,
case when U4C_PRO_RealVtaMNNeto=0 or U4C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U4C_PRO_OportunidadAhorroMN)/U4C_PRO_RealVtaMNNeto end as Rat22,
case when U5C_PRO_RealVtaMNNeto=0 or U5C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U5C_PRO_OportunidadAhorroMN)/U5C_PRO_RealVtaMNNeto end as Rat23,
case when U6C_PRO_RealVtaMNNeto=0 or U6C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U6C_PRO_OportunidadAhorroMN)/U6C_PRO_RealVtaMNNeto end as Rat24,
case when U9C_PRO_RealVtaMNNeto=0 or U9C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U9C_PRO_OportunidadAhorroMN)/U9C_PRO_RealVtaMNNeto end as Rat25,
case when U12C_PRO_RealVtaMNNeto=0 or U12C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U12C_PRO_OportunidadAhorroMN)/U12C_PRO_RealVtaMNNeto end as Rat26,
case when U15C_PRO_RealVtaMNNeto=0 or U15C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U15C_PRO_OportunidadAhorroMN)/U15C_PRO_RealVtaMNNeto end as Rat27,
case when U18C_PRO_RealVtaMNNeto=0 or U18C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U18C_PRO_OportunidadAhorroMN)/U18C_PRO_RealVtaMNNeto end as Rat28,
case when U2C_PRO_RealVtaMNNeto=0 or U2C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U2C_MAX_OportunidadAhorroMN)/U2C_PRO_RealVtaMNNeto end as Rat29,
case when U3C_PRO_RealVtaMNNeto=0 or U3C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U3C_MAX_OportunidadAhorroMN)/U3C_PRO_RealVtaMNNeto end as Rat30,
case when U4C_PRO_RealVtaMNNeto=0 or U4C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U4C_MAX_OportunidadAhorroMN)/U4C_PRO_RealVtaMNNeto end as Rat31,
case when U5C_PRO_RealVtaMNNeto=0 or U5C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U5C_MAX_OportunidadAhorroMN)/U5C_PRO_RealVtaMNNeto end as Rat32,
case when U6C_PRO_RealVtaMNNeto=0 or U6C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U6C_MAX_OportunidadAhorroMN)/U6C_PRO_RealVtaMNNeto end as Rat33,
case when U9C_PRO_RealVtaMNNeto=0 or U9C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U9C_MAX_OportunidadAhorroMN)/U9C_PRO_RealVtaMNNeto end as Rat34,
case when U12C_PRO_RealVtaMNNeto=0 or U12C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U12C_MAX_OportunidadAhorroMN)/U12C_PRO_RealVtaMNNeto end as Rat35,
case when U15C_PRO_RealVtaMNNeto=0 or U15C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U15C_MAX_OportunidadAhorroMN)/U15C_PRO_RealVtaMNNeto end as Rat36,
case when U18C_PRO_RealVtaMNNeto=0 or U18C_PRO_RealVtaMNNeto is null then 0 else 1.0*(U18C_MAX_OportunidadAhorroMN)/U18C_PRO_RealVtaMNNeto end as Rat37,
case when U2C_MAX_OportunidadAhorroMN=0 or U2C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U2C_PRO_OportunidadAhorroMN)/U2C_MAX_OportunidadAhorroMN end as Rat38,
case when U3C_MAX_OportunidadAhorroMN=0 or U3C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U3C_PRO_OportunidadAhorroMN)/U3C_MAX_OportunidadAhorroMN end as Rat39,
case when U4C_MAX_OportunidadAhorroMN=0 or U4C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U4C_PRO_OportunidadAhorroMN)/U4C_MAX_OportunidadAhorroMN end as Rat40,
case when U5C_MAX_OportunidadAhorroMN=0 or U5C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U5C_PRO_OportunidadAhorroMN)/U5C_MAX_OportunidadAhorroMN end as Rat41,
case when U6C_MAX_OportunidadAhorroMN=0 or U6C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U6C_PRO_OportunidadAhorroMN)/U6C_MAX_OportunidadAhorroMN end as Rat42,
case when U9C_MAX_OportunidadAhorroMN=0 or U9C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U9C_PRO_OportunidadAhorroMN)/U9C_MAX_OportunidadAhorroMN end as Rat43,
case when U12C_MAX_OportunidadAhorroMN=0 or U12C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U12C_PRO_OportunidadAhorroMN)/U12C_MAX_OportunidadAhorroMN end as Rat44,
case when U15C_MAX_OportunidadAhorroMN=0 or U15C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U15C_PRO_OportunidadAhorroMN)/U15C_MAX_OportunidadAhorroMN end as Rat45,
case when U18C_MAX_OportunidadAhorroMN=0 or U18C_MAX_OportunidadAhorroMN is null then 0 else 1.0*(U18C_PRO_OportunidadAhorroMN)/U18C_MAX_OportunidadAhorroMN end as Rat46,
CASE WHEN ISNULL(A.U2C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U2C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U2C,
CASE WHEN ISNULL(A.U3C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U3C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U3C,
CASE WHEN ISNULL(A.U4C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U4C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U4C,
CASE WHEN ISNULL(A.U5C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U5C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U5C,
CASE WHEN ISNULL(A.U6C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U6C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U6C,
CASE WHEN ISNULL(A.U9C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U9C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U9C,
CASE WHEN ISNULL(A.U12C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U12C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U12C,
CASE WHEN ISNULL(A.U15C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U15C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U15C,
CASE WHEN ISNULL(A.U18C_RealUUVendidas_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUVendidas,0)/ ISNULL(A.U18C_RealUUVendidas_SUC,0) END  AS TEND_UVEN_U18C,
CASE WHEN ISNULL(A.U3C_RealUUVendidas_II,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealUUVendidas,0)/ ISNULL(A.U3C_RealUUVendidas_II,0) END  AS TEND_TRI_UVEN_U6C,
CASE WHEN ISNULL(A.U3C_RealUUVendidas_SUC_III,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealUUVendidas,0)/ ISNULL(A.U3C_RealUUVendidas_SUC_III,0) END  AS TEND_TRI_UVEN_U9C,
CASE WHEN ISNULL(A.U6C_RealUUVendidas_SUCIV,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealUUVendidas,0)/ ISNULL(A.U6C_RealUUVendidas_SUCIV,0) END  AS TEND_TRI_UVEN_U12C,
CASE WHEN ISNULL(A.U9C_RealUUVendidas_V,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealUUVendidas,0)/ ISNULL(A.U9C_RealUUVendidas_V,0) END  AS TEND_TRI_UVEN_U15C,
CASE WHEN ISNULL(A.U12C_RealUUVendidas_VI,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealUUVendidas,0)/ ISNULL(A.U12C_RealUUVendidas_VI,0) END  AS TEND_TRI_UVEN_U18C,
CASE WHEN ISNULL(A.U2C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U2C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U2C,
CASE WHEN ISNULL(A.U3C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U3C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U3C,
CASE WHEN ISNULL(A.U4C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U4C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U4C,
CASE WHEN ISNULL(A.U5C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U5C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U5C,
CASE WHEN ISNULL(A.U6C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U6C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U6C,
CASE WHEN ISNULL(A.U9C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U9C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U9C,
CASE WHEN ISNULL(A.U12C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U12C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U12C,
CASE WHEN ISNULL(A.U15C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U15C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U15C,
CASE WHEN ISNULL(A.U18C_OportunidadAhorroMN_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.U18C_OportunidadAhorroMN_SUC,0) END  AS TEND_AHORR_U18C,
CASE WHEN ISNULL(A.U3C_OportunidadAhorroMN_II,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_OportunidadAhorroMN,0)/ ISNULL(A.U3C_OportunidadAhorroMN_II,0) END  AS TEND_TRI_AHORR_U6C,
CASE WHEN ISNULL(A.U3C_OportunidadAhorroMN_SUC_III,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_OportunidadAhorroMN,0)/ ISNULL(A.U3C_OportunidadAhorroMN_SUC_III,0) END  AS TEND_TRI_AHORR_U9C,
CASE WHEN ISNULL(A.U6C_OportunidadAhorroMN_SUCIV,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_OportunidadAhorroMN,0)/ ISNULL(A.U6C_OportunidadAhorroMN_SUCIV,0) END  AS TEND_TRI_AHORR_U12C,
CASE WHEN ISNULL(A.U9C_OportunidadAhorroMN_V,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_OportunidadAhorroMN,0)/ ISNULL(A.U9C_OportunidadAhorroMN_V,0) END  AS TEND_TRI_AHORR_U15C,
CASE WHEN ISNULL(A.U12C_OportunidadAhorroMN_VI,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_OportunidadAhorroMN,0)/ ISNULL(A.U12C_OportunidadAhorroMN_VI,0) END  AS TEND_TRI_AHORR_U18C,
CASE WHEN ISNULL(A.U2C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U2C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U2C,
CASE WHEN ISNULL(A.U3C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U3C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U3C,
CASE WHEN ISNULL(A.U4C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U4C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U4C,
CASE WHEN ISNULL(A.U5C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U5C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U5C,
CASE WHEN ISNULL(A.U6C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U6C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U6C,
CASE WHEN ISNULL(A.U9C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U9C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U9C,
CASE WHEN ISNULL(A.U12C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U12C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U12C,
CASE WHEN ISNULL(A.U15C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U15C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U15C,
CASE WHEN ISNULL(A.U18C_RealVtaMNNeto_SUC,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.U18C_RealVtaMNNeto_SUC,0) END  AS TEND_VTA_U18C,
CASE WHEN ISNULL(A.U3C_RealVtaMNNeto_II,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealVtaMNNeto,0)/ ISNULL(A.U3C_RealVtaMNNeto_II,0) END  AS TEND_TRI_VTA_U6C,
CASE WHEN ISNULL(A.U3C_RealVtaMNNeto_SUC_III,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealVtaMNNeto,0)/ ISNULL(A.U3C_RealVtaMNNeto_SUC_III,0) END  AS TEND_TRI_VTA_U9C,
CASE WHEN ISNULL(A.U6C_RealVtaMNNeto_SUCIV,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealVtaMNNeto,0)/ ISNULL(A.U6C_RealVtaMNNeto_SUCIV,0) END  AS TEND_TRI_VTA_U12C,
CASE WHEN ISNULL(A.U9C_RealVtaMNNeto_V,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealVtaMNNeto,0)/ ISNULL(A.U9C_RealVtaMNNeto_V,0) END  AS TEND_TRI_VTA_U15C,
CASE WHEN ISNULL(A.U12C_RealVtaMNNeto_VI,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealVtaMNNeto,0)/ ISNULL(A.U12C_RealVtaMNNeto_VI,0) END  AS TEND_TRI_VTA_U18C,
CASE WHEN ISNULL(A.U2C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_DESV_RealUUVendidas,0)/ ISNULL(A.U2C_RealUUVendidas,0) END  AS U2C_UVEN_CV,
CASE WHEN ISNULL(A.U3C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_DESV_RealUUVendidas,0)/ ISNULL(A.U3C_RealUUVendidas,0) END  AS U3C_UVEN_CV,
CASE WHEN ISNULL(A.U4C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_DESV_RealUUVendidas,0)/ ISNULL(A.U4C_RealUUVendidas,0) END  AS U4C_UVEN_CV,
CASE WHEN ISNULL(A.U5C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_DESV_RealUUVendidas,0)/ ISNULL(A.U5C_RealUUVendidas,0) END  AS U5C_UVEN_CV,
CASE WHEN ISNULL(A.U6C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_DESV_RealUUVendidas,0)/ ISNULL(A.U6C_RealUUVendidas,0) END  AS U6C_UVEN_CV,
CASE WHEN ISNULL(A.U9C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_DESV_RealUUVendidas,0)/ ISNULL(A.U9C_RealUUVendidas,0) END  AS U9C_UVEN_CV,
CASE WHEN ISNULL(A.U12C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_DESV_RealUUVendidas,0)/ ISNULL(A.U12C_RealUUVendidas,0) END  AS U12C_UVEN_CV,
CASE WHEN ISNULL(A.U15C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_DESV_RealUUVendidas,0)/ ISNULL(A.U15C_RealUUVendidas,0) END  AS U15C_UVEN_CV,
CASE WHEN ISNULL(A.U18C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_DESV_RealUUVendidas,0)/ ISNULL(A.U18C_RealUUVendidas,0) END  AS U18C_UVEN_CV,
CASE WHEN ISNULL(A.U2C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_DESV_RealUUDevueltas,0)/ ISNULL(A.U2C_RealUUDevueltas,0) END  AS U2C_DEV_CV,
CASE WHEN ISNULL(A.U3C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_DESV_RealUUDevueltas,0)/ ISNULL(A.U3C_RealUUDevueltas,0) END  AS U3C_DEV_CV,
CASE WHEN ISNULL(A.U4C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_DESV_RealUUDevueltas,0)/ ISNULL(A.U4C_RealUUDevueltas,0) END  AS U4C_DEV_CV,
CASE WHEN ISNULL(A.U5C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_DESV_RealUUDevueltas,0)/ ISNULL(A.U5C_RealUUDevueltas,0) END  AS U5C_DEV_CV,
CASE WHEN ISNULL(A.U6C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_DESV_RealUUDevueltas,0)/ ISNULL(A.U6C_RealUUDevueltas,0) END  AS U6C_DEV_CV,
CASE WHEN ISNULL(A.U9C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_DESV_RealUUDevueltas,0)/ ISNULL(A.U9C_RealUUDevueltas,0) END  AS U9C_DEV_CV,
CASE WHEN ISNULL(A.U12C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_DESV_RealUUDevueltas,0)/ ISNULL(A.U12C_RealUUDevueltas,0) END  AS U12C_DEV_CV,
CASE WHEN ISNULL(A.U15C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_DESV_RealUUDevueltas,0)/ ISNULL(A.U15C_RealUUDevueltas,0) END  AS U15C_DEV_CV,
CASE WHEN ISNULL(A.U18C_RealUUDevueltas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_DESV_RealUUDevueltas,0)/ ISNULL(A.U18C_RealUUDevueltas,0) END  AS U18C_DEV_CV,
CASE WHEN ISNULL(A.U2C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_DESV_RealUUAnuladas,0)/ ISNULL(A.U2C_RealUUAnuladas,0) END  AS U2C_ANU_CV,
CASE WHEN ISNULL(A.U3C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_DESV_RealUUAnuladas,0)/ ISNULL(A.U3C_RealUUAnuladas,0) END  AS U3C_ANU_CV,
CASE WHEN ISNULL(A.U4C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_DESV_RealUUAnuladas,0)/ ISNULL(A.U4C_RealUUAnuladas,0) END  AS U4C_ANU_CV,
CASE WHEN ISNULL(A.U5C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_DESV_RealUUAnuladas,0)/ ISNULL(A.U5C_RealUUAnuladas,0) END  AS U5C_ANU_CV,
CASE WHEN ISNULL(A.U6C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_DESV_RealUUAnuladas,0)/ ISNULL(A.U6C_RealUUAnuladas,0) END  AS U6C_ANU_CV,
CASE WHEN ISNULL(A.U9C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_DESV_RealUUAnuladas,0)/ ISNULL(A.U9C_RealUUAnuladas,0) END  AS U9C_ANU_CV,
CASE WHEN ISNULL(A.U12C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_DESV_RealUUAnuladas,0)/ ISNULL(A.U12C_RealUUAnuladas,0) END  AS U12C_ANU_CV,
CASE WHEN ISNULL(A.U15C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_DESV_RealUUAnuladas,0)/ ISNULL(A.U15C_RealUUAnuladas,0) END  AS U15C_ANU_CV,
CASE WHEN ISNULL(A.U18C_RealUUAnuladas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_DESV_RealUUAnuladas,0)/ ISNULL(A.U18C_RealUUAnuladas,0) END  AS U18C_ANU_CV,
CASE WHEN ISNULL(A.U2C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U2C_RealVtaMNNeto,0) END  AS U2C_VTA_CV,
CASE WHEN ISNULL(A.U3C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U3C_RealVtaMNNeto,0) END  AS U3C_VTA_CV,
CASE WHEN ISNULL(A.U4C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U4C_RealVtaMNNeto,0) END  AS U4C_VTA_CV,
CASE WHEN ISNULL(A.U5C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U5C_RealVtaMNNeto,0) END  AS U5C_VTA_CV,
CASE WHEN ISNULL(A.U6C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U6C_RealVtaMNNeto,0) END  AS U6C_VTA_CV,
CASE WHEN ISNULL(A.U9C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U9C_RealVtaMNNeto,0) END  AS U9C_VTA_CV,
CASE WHEN ISNULL(A.U12C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U12C_RealVtaMNNeto,0) END  AS U12C_VTA_CV,
CASE WHEN ISNULL(A.U15C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U15C_RealVtaMNNeto,0) END  AS U15C_VTA_CV,
CASE WHEN ISNULL(A.U18C_RealVtaMNNeto,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_DESV_RealVtaMNNeto,0)/ ISNULL(A.U18C_RealVtaMNNeto,0) END  AS U18C_VTA_CV,
CASE WHEN ISNULL(A.U2C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U2C_OportunidadAhorroMN,0) END  AS U2C_AHORR_CV,
CASE WHEN ISNULL(A.U3C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U3C_OportunidadAhorroMN,0) END  AS U3C_AHORR_CV,
CASE WHEN ISNULL(A.U4C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U4C_OportunidadAhorroMN,0) END  AS U4C_AHORR_CV,
CASE WHEN ISNULL(A.U5C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U5C_OportunidadAhorroMN,0) END  AS U5C_AHORR_CV,
CASE WHEN ISNULL(A.U6C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U6C_OportunidadAhorroMN,0) END  AS U6C_AHORR_CV,
CASE WHEN ISNULL(A.U9C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U9C_OportunidadAhorroMN,0) END  AS U9C_AHORR_CV,
CASE WHEN ISNULL(A.U12C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U12C_OportunidadAhorroMN,0) END  AS U12C_AHORR_CV,
CASE WHEN ISNULL(A.U15C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U15C_OportunidadAhorroMN,0) END  AS U15C_AHORR_CV,
CASE WHEN ISNULL(A.U18C_OportunidadAhorroMN,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_DESV_OportunidadAhorroMN,0)/ ISNULL(A.U18C_OportunidadAhorroMN,0) END  AS U18C_AHORR_CV,
CASE WHEN ISNULL(A.UC_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUFaltantes,0)/ ISNULL(A.UC_RealUUVendidas,0) END  AS UC_RAT_FAL_CV,
CASE WHEN ISNULL(A.U2C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_RealUUFaltantes,0)/ ISNULL(A.U2C_RealUUVendidas,0) END  AS U2C_RAT_FAL_CV,
CASE WHEN ISNULL(A.U3C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealUUFaltantes,0)/ ISNULL(A.U3C_RealUUVendidas,0) END  AS U3C_RAT_FAL_CV,
CASE WHEN ISNULL(A.U4C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_RealUUFaltantes,0)/ ISNULL(A.U4C_RealUUVendidas,0) END  AS U4C_RAT_FAL_CV,
CASE WHEN ISNULL(A.U5C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_RealUUFaltantes,0)/ ISNULL(A.U5C_RealUUVendidas,0) END  AS U5C_RAT_FAL_CV,
CASE WHEN ISNULL(A.U6C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_RealUUFaltantes,0)/ ISNULL(A.U6C_RealUUVendidas,0) END  AS U6C_RAT_FAL_CV,
CASE WHEN ISNULL(A.U9C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_RealUUFaltantes,0)/ ISNULL(A.U9C_RealUUVendidas,0) END  AS U9C_RAT_FAL_CV,
CASE WHEN ISNULL(A.U12C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_RealUUFaltantes,0)/ ISNULL(A.U12C_RealUUVendidas,0) END  AS U12C_RAT_FAL_CV,
CASE WHEN ISNULL(A.U15C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_RealUUFaltantes,0)/ ISNULL(A.U15C_RealUUVendidas,0) END  AS U15C_RAT_FAL_CV,
CASE WHEN ISNULL(A.U18C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_RealUUFaltantes,0)/ ISNULL(A.U18C_RealUUVendidas,0) END  AS U18C_RAT_FAL_CV,
CASE WHEN ISNULL(A.UC_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUDevueltas,0)/ ISNULL(A.UC_RealUUVendidas,0) END  AS UC_RAT_DEV_CV,
CASE WHEN ISNULL(A.U2C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_RealUUDevueltas,0)/ ISNULL(A.U2C_RealUUVendidas,0) END  AS U2C_RAT_DEV_CV,
CASE WHEN ISNULL(A.U3C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealUUDevueltas,0)/ ISNULL(A.U3C_RealUUVendidas,0) END  AS U3C_RAT_DEV_CV,
CASE WHEN ISNULL(A.U4C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_RealUUDevueltas,0)/ ISNULL(A.U4C_RealUUVendidas,0) END  AS U4C_RAT_DEV_CV,
CASE WHEN ISNULL(A.U5C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_RealUUDevueltas,0)/ ISNULL(A.U5C_RealUUVendidas,0) END  AS U5C_RAT_DEV_CV,
CASE WHEN ISNULL(A.U6C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_RealUUDevueltas,0)/ ISNULL(A.U6C_RealUUVendidas,0) END  AS U6C_RAT_DEV_CV,
CASE WHEN ISNULL(A.U9C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_RealUUDevueltas,0)/ ISNULL(A.U9C_RealUUVendidas,0) END  AS U9C_RAT_DEV_CV,
CASE WHEN ISNULL(A.U12C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_RealUUDevueltas,0)/ ISNULL(A.U12C_RealUUVendidas,0) END  AS U12C_RAT_DEV_CV,
CASE WHEN ISNULL(A.U15C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_RealUUDevueltas,0)/ ISNULL(A.U15C_RealUUVendidas,0) END  AS U15C_RAT_DEV_CV,
CASE WHEN ISNULL(A.U18C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_RealUUDevueltas,0)/ ISNULL(A.U18C_RealUUVendidas,0) END  AS U18C_RAT_DEV_CV,
CASE WHEN ISNULL(A.UC_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealUUAnuladas,0)/ ISNULL(A.UC_RealUUVendidas,0) END  AS UC_RAT_ANU_CV,
CASE WHEN ISNULL(A.U2C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_RealUUAnuladas,0)/ ISNULL(A.U2C_RealUUVendidas,0) END  AS U2C_RAT_ANU_CV,
CASE WHEN ISNULL(A.U3C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealUUAnuladas,0)/ ISNULL(A.U3C_RealUUVendidas,0) END  AS U3C_RAT_ANU_CV,
CASE WHEN ISNULL(A.U4C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_RealUUAnuladas,0)/ ISNULL(A.U4C_RealUUVendidas,0) END  AS U4C_RAT_ANU_CV,
CASE WHEN ISNULL(A.U5C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_RealUUAnuladas,0)/ ISNULL(A.U5C_RealUUVendidas,0) END  AS U5C_RAT_ANU_CV,
CASE WHEN ISNULL(A.U6C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_RealUUAnuladas,0)/ ISNULL(A.U6C_RealUUVendidas,0) END  AS U6C_RAT_ANU_CV,
CASE WHEN ISNULL(A.U9C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_RealUUAnuladas,0)/ ISNULL(A.U9C_RealUUVendidas,0) END  AS U9C_RAT_ANU_CV,
CASE WHEN ISNULL(A.U12C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_RealUUAnuladas,0)/ ISNULL(A.U12C_RealUUVendidas,0) END  AS U12C_RAT_ANU_CV,
CASE WHEN ISNULL(A.U15C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_RealUUAnuladas,0)/ ISNULL(A.U15C_RealUUVendidas,0) END  AS U15C_RAT_ANU_CV,
CASE WHEN ISNULL(A.U18C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_RealUUAnuladas,0)/ ISNULL(A.U18C_RealUUVendidas,0) END  AS U18C_RAT_ANU_CV,
CASE WHEN ISNULL(A.UC_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_RealVtaMNNeto,0)/ ISNULL(A.UC_RealUUVendidas,0) END  AS UC_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U2C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_RealVtaMNNeto,0)/ ISNULL(A.U2C_RealUUVendidas,0) END  AS U2C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U3C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_RealVtaMNNeto,0)/ ISNULL(A.U3C_RealUUVendidas,0) END  AS U3C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U4C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_RealVtaMNNeto,0)/ ISNULL(A.U4C_RealUUVendidas,0) END  AS U4C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U5C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_RealVtaMNNeto,0)/ ISNULL(A.U5C_RealUUVendidas,0) END  AS U5C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U6C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_RealVtaMNNeto,0)/ ISNULL(A.U6C_RealUUVendidas,0) END  AS U6C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U9C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_RealVtaMNNeto,0)/ ISNULL(A.U9C_RealUUVendidas,0) END  AS U9C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U12C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_RealVtaMNNeto,0)/ ISNULL(A.U12C_RealUUVendidas,0) END  AS U12C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U15C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_RealVtaMNNeto,0)/ ISNULL(A.U15C_RealUUVendidas,0) END  AS U15C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.U18C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_RealVtaMNNeto,0)/ ISNULL(A.U18C_RealUUVendidas,0) END  AS U18C_RAT_VTA_UNI_CV,
CASE WHEN ISNULL(A.UC_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.UC_OportunidadAhorroMN,0)/ ISNULL(A.UC_RealUUVendidas,0) END  AS UC_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U2C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U2C_OportunidadAhorroMN,0)/ ISNULL(A.U2C_RealUUVendidas,0) END  AS U2C_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U3C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U3C_OportunidadAhorroMN,0)/ ISNULL(A.U3C_RealUUVendidas,0) END  AS U3C_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U4C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U4C_OportunidadAhorroMN,0)/ ISNULL(A.U4C_RealUUVendidas,0) END  AS U4C_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U5C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U5C_OportunidadAhorroMN,0)/ ISNULL(A.U5C_RealUUVendidas,0) END  AS U5C_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U6C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U6C_OportunidadAhorroMN,0)/ ISNULL(A.U6C_RealUUVendidas,0) END  AS U6C_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U9C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U9C_OportunidadAhorroMN,0)/ ISNULL(A.U9C_RealUUVendidas,0) END  AS U9C_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U12C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U12C_OportunidadAhorroMN,0)/ ISNULL(A.U12C_RealUUVendidas,0) END  AS U12C_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U15C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U15C_OportunidadAhorroMN,0)/ ISNULL(A.U15C_RealUUVendidas,0) END  AS U15C_RAT_AHOR_UNI_CV,
CASE WHEN ISNULL(A.U18C_RealUUVendidas,0)=0 THEN 0 ELSE (1.0)* ISNULL(A.U18C_OportunidadAhorroMN,0)/ ISNULL(A.U18C_RealUUVendidas,0) END  AS U18C_RAT_AHOR_UNI_CV
INTO #KR_VEN_CAMP_TF
FROM #KR_VEN_CAMP_TOT A 
INNER JOIN #KR_TARGET_FUGA1 B ON A.AnioCampana = B.AnioCampanaT AND A.PKEbelista = B.PKEbelista AND A.CodPais = B.CodPais